try{
'use strict';var h,m=this,p=function(a){a.w=function(){return a.aa?a.aa:a.aa=new a}},aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},r=function(a){return"array"==aa(a)},v=function(a){return"string"==typeof a},ba=function(a){return"function"==aa(a)},ca=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},fa=function(a){return a[da]||(a[da]=++ea)},da="closure_uid_"+(1E9*Math.random()>>>0),ea=0,ga=function(a,b,c){return a.call.apply(a.bind,
arguments)},ha=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},w=function(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ga:ha;return w.apply(null,arguments)},ia=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=
c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},ja=Date.now||function(){return+new Date},x=function(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ka=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
var y=function(){this.e=this.e;this.c=this.c};y.prototype.e=!1;y.prototype.Y=function(){this.e||(this.e=!0,this.C())};var ka=function(a,b){a.e?b.call(void 0):(a.c||(a.c=[]),a.c.push(b))};y.prototype.C=function(){if(this.c)for(;this.c.length;)this.c.shift()()};var la=function(a){a&&"function"==typeof a.Y&&a.Y()};
var z=function(a,b){this.type=a;this.c=this.target=b;this.ca=!0};z.prototype.U=function(){this.ca=!1};var ma=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},oa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c;c=m.document.createElement("div");return a.replace(na,function(a,e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var g=Number("0"+e.substr(1));isNaN(g)||(f=String.fromCharCode(g))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},pa=function(a){return a.replace(/&([^;]+);/g,function(a,
c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return a}})},na=/&([^;\s<&]+);?/g,A=function(a){return null==a?"":String(a)},qa=function(a,b){return a<b?-1:a>b?1:0},ra=function(a){isFinite(a)&&(a=String(a));return v(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};
var sa=function(a){z.call(this,a);this.d=0;this.a=null;this.g=this.m="";this.k=0;this.e=""};x(sa,z);var ta=function(a,b,c,d,e){var f=new sa("clip_changed");f.a=a;f.d=b;f.m=c;f.g=d;e&&(f.k=e.g,f.e=e.v());return f};sa.prototype.L=function(){return A(this.a&&this.a.v()||null)};
var ua;var B=Array.prototype,va=B.indexOf?function(a,b,c){return B.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(v(a))return v(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},wa=B.forEach?function(a,b,c){B.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},xa=B.filter?function(a,b,c){return B.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=v(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var l=g[k];b.call(c,l,k,a)&&(e[f++]=l)}return e},ya=B.map?function(a,b,c){return B.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=v(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},za=function(a){return B.concat.apply(B,arguments)},Aa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ba=function(a,b){for(var c=b||function(){return ca(g)?"o"+fa(g):(typeof g).charAt(0)+g},d={}, e=0,f=0;f<a.length;){var g=a[f++],k=c(g);Object.prototype.hasOwnProperty.call(d,k)||(d[k]=!0,a[e++]=g)}a.length=e},Ca=function(a,b){return a>b?1:a<b?-1:0};
var Da=m.JSON.stringify;var Ea=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Fa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Ga="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Ha=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ga.length;f++)c=Ga[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Ia=function(a){var b=arguments.length;if(1==b&&r(arguments[0]))return Ia.apply(null, arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};
var C=function(){},D=function(a,b,c,d){a.c={};b||(b=[]);a.m=void 0;a.e=-1;a.a=b;t:{if(a.a.length){b=a.a.length-1;var e=a.a[b];if(e&&"object"==typeof e&&"number"!=typeof e.length){a.g=b-a.e;a.d=e;break t}}-1<c?(a.g=c,a.d=a.a[c+a.e]={}):a.g=Number.MAX_VALUE}if(d)for(c=0;c<d.length;c++)b=d[c],b<a.g?(b+=a.e,a.a[b]=a.a[b]||[]):a.d[b]=a.d[b]||[]},E=function(a,b){return b<a.g?a.a[b+a.e]:a.d[b]},F=function(a,b,c){b<a.g?a.a[b+a.e]=c:a.d[b]=c},G=function(a,b,c){if(!a.c[c]){var d=E(a,c);d&&(a.c[c]=new b(d))}return a.c[c]},
H=function(a,b,c){var d=c?c.a:c;a.c[b]=c;F(a,b,d)};C.prototype.i=function(){return m.JSON&&m.JSON.stringify?m.JSON.stringify(this.a):Da(this.a)};C.prototype.toString=function(){return this.a.toString()};
var Ka=function(a){var b=Ja,c=b.c;if(b.d){if(b.a)return a.c[c]||(a.c[c]=ya(a.d[c]||[],function(a){return new b.a(a)})),a.c[c]}else if(b.a)return!a.c[c]&&a.d[c]&&(a.c[c]=new b.a(a.d[c])),a.c[c];return a.d[c]},La=function(a){var b;if(r(a)){for(var c=Array(a.length),d=0;d<a.length;d++)null!=(b=a[d])&&(c[d]="object"==typeof b?La(b):b);return c}c={};for(d in a)null!=(b=a[d])&&(c[d]="object"==typeof b?La(b):b);return c};
var Ma=function(a){D(this,a,-1,null)};x(Ma,C);var I=function(a){return G(a,Na,2)},Na=function(a){D(this,a,-1,null)};x(Na,C);var Oa=function(a){return E(a,1)};var Pa=function(a){D(this,a,-1,null)};x(Pa,C);Pa.prototype.v=function(){return E(this,1)};var Qa=function(a){D(this,a,-1,null)};x(Qa,C);Qa.prototype.getTitle=function(){return E(this,1)};Qa.prototype.setTitle=function(a){F(this,1,a)};var Ra=function(a){D(this,a,-1,null)};x(Ra,C);var Sa=function(a){D(this,a,-1,null)};x(Sa,C);var Ua=function(a){D(this,a,22,Ta)};x(Ua,C);var Ta=[3];Ua.prototype.L=function(){return G(this,Pa,1)};var Va=function(a){D(this,a,-1,null)};x(Va,C);var Wa=function(a){this.a=a||new Va};Wa.prototype.i=function(){return this.a.i()};var J;t:{var Xa=m.navigator;if(Xa){var Ya=Xa.userAgent;if(Ya){J=Ya;break t}}J=""};var Za=-1!=J.indexOf("Opera")||-1!=J.indexOf("OPR"),K=-1!=J.indexOf("Trident")||-1!=J.indexOf("MSIE"),$a=-1!=J.indexOf("Gecko")&&-1==J.toLowerCase().indexOf("webkit")&&!(-1!=J.indexOf("Trident")||-1!=J.indexOf("MSIE")),L=-1!=J.toLowerCase().indexOf("webkit"),ab=function(){var a=m.document;return a?a.documentMode:void 0},bb=function(){var a="",b;if(Za&&m.opera)return a=m.opera.version,ba(a)?a():a;$a?b=/rv\:([^\);]+)(\)|;)/:K?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:L&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(J))?
a[1]:"");return K&&(b=ab(),b>parseFloat(a))?String(b):a}(),cb={},M=function(a){var b;if(!(b=cb[a])){b=0;for(var c=ma(String(bb)).split("."),d=ma(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"",l=/(\d*)(\D*)/g,q=/(\d*)(\D*)/g;do{var n=l.exec(g)||["","",""],t=q.exec(k)||["","",""];if(0==n[0].length&&0==t[0].length)break;b=qa(0==n[1].length?0:parseInt(n[1],10),0==t[1].length?0:parseInt(t[1],10))||qa(0==n[2].length,0==t[2].length)||qa(n[2],t[2])}while(0== b)}b=cb[a]=0<=b}return b},db=m.document,fb=db&&K?ab()||("CSS1Compat"==db.compatMode?parseInt(bb,10):5):void 0;
var gb=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,jb=function(a){if(hb){hb=!1;var b=m.location;if(b){var c=b.href;if(c&&(c=ib(jb(c)[3]||null))&&c!=b.hostname)throw hb=!0,Error();}}return a.match(gb)},hb=L,ib=function(a){return a?decodeURI(a):a},kb=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?decodeURIComponent(g.replace(/\+/g, " ")):"")}};
var lb="StopIteration"in m?m.StopIteration:Error("StopIteration"),mb=function(){};mb.prototype.next=function(){throw lb;};mb.prototype.R=function(){return this};var N=function(a,b){this.c={};this.a=[];this.e=this.d=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){if(a instanceof N)d=a.M(),c=a.n();else{var c=[],e=0;for(d in a)c[e++]=d;d=c;c=Fa(a)}for(e=0;e<d.length;e++)this.set(d[e],c[e])}};N.prototype.n=function(){nb(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.c[this.a[b]]);return a};N.prototype.M=function(){nb(this);return this.a.concat()};
N.prototype.N=function(){return 0==this.d};N.prototype.remove=function(a){return O(this.c,a)?(delete this.c[a],this.d--,this.e++,this.a.length>2*this.d&&nb(this),!0):!1};var nb=function(a){if(a.d!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];O(a.c,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.d!=a.a.length){for(var e={},c=b=0;b<a.a.length;)d=a.a[b],O(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}};h=N.prototype;h.get=function(a,b){return O(this.c,a)?this.c[a]:b};
h.set=function(a,b){O(this.c,a)||(this.d++,this.a.push(a),this.e++);this.c[a]=b};h.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new N(this)};h.R=function(a){nb(this);var b=0,c=this.a,d=this.c,e=this.e,f=this,g=new mb;g.next=function(){for(;;){if(e!=f.e)throw Error("The map has changed since the iterator was created");if(b>=c.length)throw lb;var g=c[b++];return a?g:d[g]}};return g}; var O=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var ob=function(a){if("function"==typeof a.n)return a.n();if(v(a))return a.split("");var b=aa(a);if("array"==b||"object"==b&&"number"==typeof a.length){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Fa(a)};var P=function(a,b){var c;a instanceof P?(this.F=void 0!==b?b:a.F,pb(this,a.B),this.I=a.I,this.p=a.p,qb(this,a.J),this.o=a.o,rb(this,a.a.clone()),this.D=a.D):a&&(c=jb(String(a)))?(this.F=!!b,pb(this,c[1]||"",!0),this.I=sb(c[2]||""),this.p=sb(c[3]||"",!0),qb(this,c[4]),this.o=sb(c[5]||"",!0),rb(this,c[6]||"",!0),this.D=sb(c[7]||"")):(this.F=!!b,this.a=new tb(null,0,this.F))};h=P.prototype;h.B="";h.I="";h.p="";h.J=null;h.o="";h.D="";h.F=!1;
h.toString=function(){var a=[],b=this.B;b&&a.push(ub(b,vb,!0),":");if(b=this.p){a.push("//");var c=this.I;c&&a.push(ub(c,vb,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.J;null!=b&&a.push(":",String(b))}if(b=this.o)this.p&&"/"!=b.charAt(0)&&a.push("/"),a.push(ub(b,"/"==b.charAt(0)?wb:xb,!0));(b=this.a.toString())&&a.push("?",b);(b=this.D)&&a.push("#",ub(b,yb));return a.join("")};h.clone=function(){return new P(this)};
var pb=function(a,b,c){a.B=c?sb(b,!0):b;a.B&&(a.B=a.B.replace(/:$/,""))},qb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.J=b}else a.J=null},rb=function(a,b,c){b instanceof tb?(a.a=b,zb(a.a,a.F)):(c||(b=ub(b,Ab)),a.a=new tb(b,0,a.F))},Bb=function(a){return a instanceof P?a.clone():new P(a,void 0)},sb=function(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""},ub=function(a,b,c){return v(a)?(a=encodeURI(a).replace(b,Cb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},Cb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},vb=/[#\/\?@]/g,xb=/[\#\?:]/g,wb=/[\#\?]/g,Ab=/[\#\?@]/g,yb=/#/g,tb=function(a,b,c){this.a=a||null;this.c=!!c},Q=function(a){a.h||(a.h=new N,a.l=0,a.a&&kb(a.a,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};h=tb.prototype;h.h=null;h.l=null;h.add=function(a,b){Q(this);this.a=null;a=Db(this,a);var c=this.h.get(a);c||this.h.set(a,c=[]);c.push(b);this.l++;return this};
h.remove=function(a){Q(this);a=Db(this,a);return O(this.h.c,a)?(this.a=null,this.l-=this.h.get(a).length,this.h.remove(a)):!1};h.N=function(){Q(this);return 0==this.l};var Eb=function(a,b){Q(a);b=Db(a,b);return O(a.h.c,b)};h=tb.prototype;h.M=function(){Q(this);for(var a=this.h.n(),b=this.h.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
h.n=function(a){Q(this);var b=[];if(v(a))Eb(this,a)&&(b=za(b,this.h.get(Db(this,a))));else{a=this.h.n();for(var c=0;c<a.length;c++)b=za(b,a[c])}return b};h.set=function(a,b){Q(this);this.a=null;a=Db(this,a);Eb(this,a)&&(this.l-=this.h.get(a).length);this.h.set(a,[b]);this.l++;return this};h.get=function(a,b){var c=a?this.n(a):[];return 0<c.length?String(c[0]):b};
h.toString=function(){if(this.a)return this.a;if(!this.h)return"";for(var a=[],b=this.h.M(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.n(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}return this.a=a.join("&")};h.clone=function(){var a=new tb;a.a=this.a;this.h&&(a.h=this.h.clone(),a.l=this.l);return a};
var Db=function(a,b){var c=String(b);a.c&&(c=c.toLowerCase());return c},zb=function(a,b){b&&!a.c&&(Q(a),a.a=null,a.h.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),this.remove(e),0<a.length&&(this.a=null,this.h.set(Db(this,e),Aa(a)),this.l+=a.length))},a));a.c=b};
var Fb=function(a){this.a=a||new Qa;F(this.a,3,E(this.a,3))};Fb.prototype.getTitle=function(){return A(this.a.getTitle())};Fb.prototype.setTitle=function(a){this.a.setTitle(a)};Fb.prototype.i=function(){return this.a.i()};Ia("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));Ia("action","cite","data","formaction","href","manifest","poster","src");Ia("embed","iframe","link","object","script","style","template");var Gb=function(a){this.a=new N;if(a){a=ob(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}},Hb=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+fa(a):b.substr(0,1)+a};h=Gb.prototype;h.add=function(a){this.a.set(Hb(a),a)};h.removeAll=function(a){a=ob(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};h.remove=function(a){return this.a.remove(Hb(a))};h.N=function(){return this.a.N()};h.n=function(){return this.a.n()};h.clone=function(){return new Gb(this)};h.R=function(){return this.a.R(!1)};
var Jb=function(a,b,c,d,e){"number"==typeof e||Ib++;this.d=d||ja();this.e=a;this.g=b;this.c=c;delete this.a};Jb.prototype.a=null;var Ib=0;Jb.prototype.getMessage=function(){return this.g};var Kb=function(a){this.e=a;this.c=this.d=this.a=null},Lb=function(a,b){this.name=a;this.value=b};Lb.prototype.toString=function(){return this.name};var Mb=new Lb("SHOUT",1200),Nb=new Lb("SEVERE",1E3),Ob=new Lb("WARNING",900),Pb=new Lb("INFO",800),Qb=new Lb("CONFIG",700);Kb.prototype.getChildren=function(){this.c||(this.c={});return this.c};var Rb=function(a){return a.d?a.d:a.a?Rb(a.a):null};
Kb.prototype.log=function(a,b,c){if(a.value>=Rb(this).value)for(ba(b)&&(b=b()),a=new Jb(a,String(b),this.e),c&&(a.a=c),c="log:"+a.getMessage(),m.console&&(m.console.timeStamp?m.console.timeStamp(c):m.console.markTimeline&&m.console.markTimeline(c)),m.msWriteProfilerMark&&m.msWriteProfilerMark(c),c=this;c;)c=c.a}; var Sb={},Tb=null,Ub=function(){Tb||(Tb=new Kb(""),Sb[""]=Tb,Tb.d=Qb)},R=function(a){Ub();var b;if(!(b=Sb[a])){b=new Kb(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=R(a.substr(0,c));c.getChildren()[d]=b;b.a=c;Sb[a]=b}return b};
R("gws.collections.models.IndexedClips");var Vb=!K||K&&9<=fb,Wb=K&&!M("9");!L||M("528");$a&&M("1.9b")||K&&M("8")||Za&&M("9.5")||L&&M("528");$a&&!M("8")||K&&M("9");var Zb=function(a){Zb[" "](a);return a};Zb[" "]=function(){};var $b=function(a,b){z.call(this,a?a.type:"");this.c=this.target=null;this.clientY=this.clientX=this.T=this.S=0;this.a=this.state=null;if(a){this.a=a;this.type=a.type;this.target=a.target||a.srcElement;this.c=b;var c=a.relatedTarget;if(c&&$a)try{Zb(c.nodeName)}catch(d){}Object.defineProperties?Object.defineProperties(this,{S:{configurable:!0,enumerable:!0,get:this.Z,set:this.ia},T:{configurable:!0,enumerable:!0,get:this.$,set:this.ja}}):(this.S=this.Z(),this.T=this.$());this.clientX=void 0!==a.clientX?
a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;a.defaultPrevented&&this.U()}};x($b,z);h=$b.prototype;h.U=function(){$b.K.U.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Wb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};h.Z=function(){return L||void 0!==this.a.offsetX?this.a.offsetX:this.a.layerX};h.ia=function(a){Object.defineProperties(this,{S:{writable:!0,enumerable:!0,configurable:!0,value:a}})}; h.$=function(){return L||void 0!==this.a.offsetY?this.a.offsetY:this.a.layerY};h.ja=function(a){Object.defineProperties(this,{T:{writable:!0,enumerable:!0,configurable:!0,value:a}})};
var ac="closure_listenable_"+(1E6*Math.random()|0),bc=function(a){return!(!a||!a[ac])},cc=0;var dc=function(a,b,c,d,e){this.H=a;this.proxy=null;this.src=b;this.type=c;this.P=!!d;this.Q=e;this.V=++cc;this.removed=this.O=!1},ec=function(a){a.removed=!0;a.H=null;a.proxy=null;a.src=null;a.Q=null};var fc=function(a){this.src=a;this.a={};this.c=0};fc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.c++);var g=gc(a,b,d,e);-1<g?(b=a[g],c||(b.O=!1)):(b=new dc(b,this.src,f,!!d,e),b.O=c,a.push(b));return b};fc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=gc(e,b,c,d);return-1<b?(ec(e[b]),B.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.c--),!0):!1};
var hc=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=a.a[c],e=va(d,b),f;(f=0<=e)&&B.splice.call(d,e,1);f&&(ec(b),0==a.a[c].length&&(delete a.a[c],a.c--));return f};fc.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,ec(d[e]);delete this.a[c];this.c--}return b}; var ic=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=gc(a,c,d,e));return-1<b?a[b]:null},gc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.H==b&&f.P==!!c&&f.Q==d)return e}return-1};
var jc="closure_lm_"+(1E6*Math.random()|0),kc={},lc=0,mc=function(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)mc(a,b[f],c,d,e);return null}c=nc(c);return bc(a)?a.listen(b,c,d,e):oc(a,b,c,!1,d,e)},oc=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=!!e,k=pc(a);k||(a[jc]=k=new fc(a));c=k.add(b,c,d,e,f);if(c.proxy)return c;d=qc();c.proxy=d;d.src=a;d.H=c;a.addEventListener?a.addEventListener(b.toString(),d,g):a.attachEvent(rc(b.toString()),d);lc++;return c},qc=function(){var a=sc,
b=Vb?function(c){return a.call(b.src,b.H,c)}:function(c){c=a.call(b.src,b.H,c);if(!c)return c};return b},tc=function(a,b,c,d,e){if(r(b)){for(var f=0;f<b.length;f++)tc(a,b[f],c,d,e);return null}c=nc(c);return bc(a)?a.s.add(String(b),c,!0,d,e):oc(a,b,c,!0,d,e)},uc=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)uc(a,b[f],c,d,e);else c=nc(c),bc(a)?a.unlisten(b,c,d,e):a&&(a=pc(a))&&(b=ic(a,b,c,!!d,e))&&vc(b)},vc=function(a){if("number"==typeof a||!a||a.removed)return!1;var b=a.src;if(bc(b))return hc(b.s,
a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.P):b.detachEvent&&b.detachEvent(rc(c),d);lc--;(c=pc(b))?(hc(c,a),0==c.c&&(c.src=null,b[jc]=null)):ec(a);return!0},rc=function(a){return a in kc?kc[a]:kc[a]="on"+a},xc=function(a,b,c,d){var e=!0;if(a=pc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.P==c&&!f.removed&&(f=wc(f,d),e=e&&!1!==f)}return e},wc=function(a,b){var c=a.H,d=a.Q||a.src;a.O&&vc(a);return c.call(d,b)},sc=function(a,b){if(a.removed)return!0;
if(!Vb){var c;if(!(c=b))t:{c=["window","event"];for(var d=m,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new $b(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(g){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.c;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;0<=k;k--){c.c=e[k];var l=xc(e[k],f,!0,c),d=d&&l}for(k=0;k<e.length;k++)c.c=e[k],l=xc(e[k],f,!1,c),d=d&&l}return d}return wc(a,new $b(b, this))},pc=function(a){a=a[jc];return a instanceof fc?a:null},yc="__closure_events_fn_"+(1E9*Math.random()>>>0),nc=function(a){if(ba(a))return a;a[yc]||(a[yc]=function(b){return a.handleEvent(b)});return a[yc]};
var S=function(a){y.call(this);this.d=a;this.a={}};x(S,y);var zc=[];S.prototype.listen=function(a,b,c,d){r(b)||(b&&(zc[0]=b.toString()),b=zc);for(var e=0;e<b.length;e++){var f=mc(a,b[e],c||this.handleEvent,d||!1,this.d||this);if(!f)break;this.a[f.V]=f}return this};var Ac=function(a,b,c,d,e,f){if(r(c))for(var g=0;g<c.length;g++)Ac(a,b,c[g],d,e,f);else(b=tc(b,c,d||a.handleEvent,e,f||a.d||a))&&(a.a[b.V]=b)};
S.prototype.unlisten=function(a,b,c,d,e){if(r(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.d||this,c=nc(c),d=!!d,b=bc(a)?ic(a.s,String(b),c,d,e):a?(a=pc(a))?ic(a,b,c,d,e):null:null,b&&(vc(b),delete this.a[b.V]);return this};S.prototype.removeAll=function(){Ea(this.a,vc);this.a={}};S.prototype.C=function(){S.K.C.call(this);this.removeAll()};S.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};
R("gws.collections.models.IndexedFolios");var Bc=function(){};p(Bc);var Cc={0:"c_",1:"f_",2:"d_",3:"g_",4:"lc_",5:"lf_"},Dc=function(a){return Cc[a]+(839808*a+Math.floor(839808*Math.random())).toString(36)+ja().toString(36)};var Ec=function(a,b,c){z.call(this,c||"TRANSACTION_COMMIT");this.g=a||0;(a=b)||(Bc.w(),a=Dc(2));this.e=a;this.a=[];this.d=[]};x(Ec,z);Ec.prototype.v=function(){return this.e};var T=function(){y.call(this);this.s=new fc(this);this.ea=this;this.g=null};x(T,y);T.prototype[ac]=!0;h=T.prototype;h.addEventListener=function(a,b,c,d){mc(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){uc(this,a,b,c,d)};
h.A=function(a){var b,c=this.g;if(c)for(b=[];c;c=c.g)b.push(c);var c=this.ea,d=a.type||a;if(v(a))a=new z(a,c);else if(a instanceof z)a.target=a.target||c;else{var e=a;a=new z(d,c);Ha(a,e)}var e=!0,f;if(b)for(var g=b.length-1;0<=g;g--)f=a.c=b[g],e=Fc(f,d,!0,a)&&e;f=a.c=c;e=Fc(f,d,!0,a)&&e;e=Fc(f,d,!1,a)&&e;if(b)for(g=0;g<b.length;g++)f=a.c=b[g],e=Fc(f,d,!1,a)&&e;return e};h.C=function(){T.K.C.call(this);this.s&&this.s.removeAll(void 0);this.g=null};
h.listen=function(a,b,c,d){return this.s.add(String(a),b,!1,c,d)};h.unlisten=function(a,b,c,d){return this.s.remove(String(a),b,c,d)};var Fc=function(a,b,c,d){b=a.s.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.removed&&g.P==c){var k=g.H,l=g.Q||g.src;g.O&&hc(a.s,g);e=!1!==k.call(l,d)&&e}}return e&&0!=d.ca};
var Gc=function(){T.call(this)};x(Gc,T);var Hc=function(a){T.call(this);this.a=a};x(Hc,Gc);Hc.prototype.v=function(){return this.a.L()?A(this.a.L().v()):""};Hc.prototype.i=function(){return this.a.i()};var Ic=".0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".split(""),Jc={},Kc;for(Kc in Ic)Jc[Ic[Kc]]=Kc;for(var Lc in Jc);var U=function(a,b){this.width=a;this.height=b};U.prototype.clone=function(){return new U(this.width,this.height)};var Mc=function(a){return a.width*a.height};U.prototype.N=function(){return!Mc(this)};U.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
var Nc=function(a){this.a=a||new Ma;if(!I(this.a)){a=this.a;var b=new Na;H(a,2,b)}G(this.a,Na,3)||(a=this.a,b=new Na,H(a,3,b));this.c=new P(A(Oa(I(this.a))));new P(A(Oa(G(this.a,Na,3))).replace(/^\/\//,"https://"))};Nc.prototype.i=function(){return this.a.i()};
var Oc=function(a){this.a=a||new Ra};Oc.prototype.i=function(){return this.a.i()};var Pc=function(a){this.a=a||new Sa};Pc.prototype.i=function(){return this.a.i()};var Qc=function(a){D(this,a,-1,null)};x(Qc,C);var Ja=new function(){this.c=71309500;this.a=Qc;this.d=0}(function(a,b){var c,d=E(b,1),e=E(b,2),f;if(f=c=b.getLocation())f={latitude:E(c,1),longitude:E(c,2)},a&&(f.da=c);c={la:d,ma:e,location:f};a&&(c.da=b);return c});Qc.prototype.getLocation=function(){return G(this,Rc,3)};var Rc=function(a){D(this,a,-1,null)};x(Rc,C);
var W=function(a){Hc.call(this,a||new Ua);this.d=Sc(this);this.m=V(this);a=this.a;if(!a.c[3]){for(var b=E(a,3),c=[],d=0;d<b.length;d++)c[d]=new Va(b[d]);a.c[3]=c}a=a.c[3];for(b=0;b<a.length;b++)c=new Wa(a[b]),G(c.a,Pa,1).v();a=G(this.a,Sa,10);!this.k&&a&&(this.k=new Pc(a));this.k=this.k||null;a=G(this.a,Ra,13);!this.G&&a&&(this.G=new Oc(a));this.G=this.G||null;new Gb;this.v()||(Bc.w(),a=Dc(0),this.a.L()||(b=new Pa,H(this.a,1,b)),b=this.a.L(),F(b,1,a))};x(W,Hc);R("gws.collections.models.ClipModel");
W.prototype.clone=function(){var a;a=this.a;a=new a.constructor(La(a.a));return new W(a)};var Sc=function(a){var b=G(a.a,Ma,5);!a.d&&b&&(a.d=new Nc(b));return a.d||null},V=function(a){var b=G(a.a,Qa,6);!a.m&&b&&(a.m=new Fb(b));return a.m||null};W.prototype.getTitle=function(){return V(this)?V(this).getTitle().toString():""};
W.prototype.setTitle=function(a,b){var c=b||new Ec;if(V(this).getTitle()==a)return!1;var d=V(this).i(),e=V(this);e.setTitle(a);var f=ja();F(this.a,8,f);d=ta(this,204,d,e.i(),c);c.a.push(d);c.d.push(this);this.A(d);c!=b&&0<c.a.length&&this.A(c);return!0};var Tc=function(a,b){var c=new Ec,d=E(a.a,4);E(a.a,4)!=b&&(F(a.a,4,b),d=ta(a,206,""+d,""+b,c),c.a.push(d),c.d.push(a),a.A(d),void 0!=c&&0<c.a.length&&a.A(c))};W.prototype.toString=function(){return"ClipModel:"+this.v()}; W.prototype.getLocation=function(){var a=Ka(this.a);return a&&(a=a.getLocation())?A(E(a,1).toFixed(4)+","+E(a,2).toFixed(4)):""};
var Uc=!$a&&!K||K&&K&&9<=fb||$a&&M("1.9.1"),Vc=K&&!M("9"),Wc=K||Za||L;var Xc=function(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0};Xc.prototype.clone=function(){return new Xc(this.x,this.y)};Xc.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};var Yc=function(a){return Uc&&void 0!=a.children?a.children:xa(a.childNodes,function(a){return 1==a.nodeType})},Zc=function(a){var b;if(Wc&&!(K&&M("9")&&!M("10")&&m.SVGElement&&a instanceof m.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return ca(b)&&1==b.nodeType?b:null},$c=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document},ad={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},bd={IMG:" ",BR:"\n"},dd=function(a){if(Vc&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");
else{var b=[];cd(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Vc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a},cd=function(a,b,c){if(!(a.nodeName in ad))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in bd)b.push(bd[a.nodeName]);else for(a=a.firstChild;a;)cd(a,b,c),a=a.nextSibling},ed=function(a){this.a=a||m.document||document};ed.prototype.getChildren=Yc;
var X=function(a,b){var c=$c(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""},fd=function(a,b){return X(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]},gd=function(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}K&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);
return b},id=function(a){var b=hd;if("none"!=fd(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a},hd=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=L&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=gd(a),new U(a.right-a.left,a.bottom-a.top)):new U(b,c)};
var jd=function(a){var b;do b=a,a=-1!=a.indexOf("&")?"document"in m?oa(a):pa(a):a;while(a!=b);return a};var kd=function(){this.a=["ad","advertisement","ads","sponsor","sponsored"]};kd.prototype.filter=function(a){for(;a;){var b;a.classList?b=a.classList:(b=a.className,b=v(b)&&b.match(/\S+/g)||[]);for(var c=0;c<b.length;++c)for(var d=b[c].split(/\W+/),e=0;e<d.length;++e)if(0<=va(this.a,d[e].toLowerCase()))return!1;a=Zc(a)}return!0};
var ld=function(a){y.call(this);this.g=a;this.a={};this.d={}};x(ld,y);ld.prototype.C=function(){this.unlisten();ld.K.C.call(this)};ld.prototype.listen=function(a,b){var c=w(b,this.g);a.addListener(c);var d=fa(a);d in this.a?this.d[d].add(c):(this.a[d]=a,this.d[d]=new Gb([c]));return this};ld.prototype.unlisten=function(a){if(a){var b=fa(a);if(b in this.a){var c=this.d[b].n();wa(c,a.removeListener,a);delete this.d[b];delete this.a[b]}}else Ea(this.a,this.unlisten,this)};
var md=function(){T.call(this);this.m=new S(this);ka(this,ia(la,this.m))};x(md,T);md.prototype.d=function(a){this.g=a};var nd=function(a){this.a=a},od=function(a,b){return a==b?0:a.a-b.a};var pd=function(){this.a=[]};pd.prototype.filter=function(a){for(var b=0;b<this.a.length;++b)if(!this.a[b].filter(a))return!1;return!0};var qd=function(a,b){var c=a.c(b);if(0==c.length)return null;for(var d=c[0],e=1;e<c.length;++e){var f=c[e];f.a>d.a&&(d=f)}return d};pd.prototype.c=function(a){return Y(this,a.getElementsByTagName("*"))};var Y=function(a,b,c){for(var d=[],e=b.length,f=0;f<e;++f){var g=a.d(b[f],c);g&&d.push(g)}return d};pd.prototype.d=function(){return null};
var rd=function(a,b,c,d){this.a=a;this.c=b;this.d=c;this.e=d};x(rd,nd);var sd=function(){};sd.prototype.filter=function(a){for(;a;){if("none"==X(a,"display"))return!1;var b=id(a);if("hidden"==X(a,"overflow")&&b.N()||"hidden"==X(a,"visibility"))return!1;a=Zc(a)}return!0};var td=function(){this.a=[];this.a.push(new kd);this.a.push(new sd)};x(td,pd);p(td);var ud=R("image.collections.extension.DocumentImageExtractor"),vd={".gif":.5},wd=function(){this.ba=0;this.X={}};td.prototype.c=function(a){return Y(this,a.getElementsByTagName("*"),new wd)};
td.prototype.d=function(a,b){var c=null;switch(a.tagName.toLowerCase()){case "meta":c=xd(a,1,"property","og:image","content")||xd(a,.9,"name","msapplication-tileimage","content")||xd(a,.8,"name","twitter:image","content")||yd(a);break;case "link":c=xd(a,.7,"rel","apple-touch-icon","href")||xd(a,.6,"rel","image_src","href")||yd(a);break;case "img":if(this.filter(a))t:{if((c=a.src)&&0!=c.lastIndexOf("data:",0)){var d=new U(a.naturalWidth,a.naturalHeight),e=id(a),f=Mc(d)<Mc(e)?d:e;if(f.width&&f.height){f=
zd(a);c=new rd(f,c,d,e);break t}}c=null}break;default:if(this.filter(a)&&30>b.ba){t:{c=X(a,"background-image");d=X(a,"background-repeat");e=X(a,"background-size");if(d=c&&("no-repeat"==d||"cover"==e)&&0==c.lastIndexOf("url(",0))d=c.length-1,d=0<=d&&c.indexOf(")",d)==d;if(d&&(c=c.substr(4,c.length-5))&&0!=c.lastIndexOf("data:",0)&&(d=id(a),d.width&&d.height)){for(var e=zd(a),f=Yc(a),g=0;g<f.length;++g){var k=f[g];if("none"!=X(k,"display")&&Mc(id(k))>.1*Mc(d)){e*=.1;break}}c=new rd(e,c,void 0,d);break t}c=
null}c&&++b.ba}}if(!c)return null;e=c.e||c.d;if(c.c!=document.location.href&&(100>e.width||100>e.height))return null;d=c.a;d/=1+Math.exp(-1E-5*Mc(e));e=e.width/e.height;1>e&&(e=1/e);2<e&&(d*=.8);e=c.c;try{var l=$c(a).documentURI,f=e;l instanceof P||(l=Bb(l));f instanceof P||(f=Bb(f));var g=l,l=f,q=g.clone(),n=!!l.B;n?pb(q,l.B):n=!!l.I;n?q.I=l.I:n=!!l.p;n?q.p=l.p:n=null!=l.J;var t=l.o;if(n)qb(q,l.J);else if(n=!!l.o){if("/"!=t.charAt(0))if(g.p&&!g.o)t="/"+t;else{var u=q.o.lastIndexOf("/");-1!=u&&(t=
q.o.substr(0,u+1)+t)}u=t;if(".."==u||"."==u)t="";else if(-1!=u.indexOf("./")||-1!=u.indexOf("/.")){for(var Xb=0==u.lastIndexOf("/",0),eb=u.split("/"),u=[],f=0;f<eb.length;){var Yb=eb[f++];"."==Yb?Xb&&f==eb.length&&u.push(""):".."==Yb?((1<u.length||1==u.length&&""!=u[0])&&u.pop(),Xb&&f==eb.length&&u.push("")):(u.push(Yb),Xb=!0)}t=u.join("/")}else t=u}n?q.o=t:n=""!==l.a.toString();n?rb(q,sb(l.a.toString())):n=!!l.D;n&&(q.D=l.D);e=q.toString()}catch(fe){return ud&&ud.log(Pb,"Cannot resolve url: "+e,
void 0),null}q=A(ib(jb(e)[5]||null));n=q.lastIndexOf(".");0<n&&(q=vd[q.slice(n)])&&(d*=q);if(e in b.X&&b.X[e]>d)return null;b.X[e]=d;return new rd(d,e,c.d,c.e)};
var xd=function(a,b,c,d,e){if(A(a.getAttribute(c)).toLowerCase()==d.toLowerCase()){c=a.getAttribute(e);if(!c||0==c.lastIndexOf("data:",0))return null;d=ra(a.getAttribute("data-google-stars-image-width"));e=ra(a.getAttribute("data-google-stars-image-height"));if(d&&e)return a=$c(a),"/"!=ib(jb(a.documentURI)[5]||null)&&-1==a.body.innerHTML.indexOf(c)&&(b*=.5),new rd(b,c,new U(d,e))}return null},yd=function(a){var b=a.getAttribute("itemprop");if(b&&"thumbnailurl"==b.toLowerCase()){b=a.getAttribute("href")||
a.getAttribute("content");if(!b||0==b.lastIndexOf("data:",0))return null;var c=ra(a.getAttribute("data-google-stars-image-width"));a=ra(a.getAttribute("data-google-stars-image-height"));if(c&&a)return new rd(.55,b,new U(c,a))}return null},zd=function(a){var b=$c(a);fd(a,"position");var c=new Xc(0,0),d;d=b?$c(b):document;var e;(e=!K||K&&9<=fb)||(e="CSS1Compat"==(d?new ed($c(d)):ua||(ua=new ed)).a.compatMode);a!=(e?d.documentElement:d.body)&&(a=gd(a),d=(b?new ed($c(b)):ua||(ua=new ed)).a,b=L||"CSS1Compat"!=
d.compatMode?d.body||d.documentElement:d.documentElement,d=d.parentWindow||d.defaultView,b=K&&M("10")&&d.pageYOffset!=b.scrollTop?new Xc(b.scrollLeft,b.scrollTop):new Xc(d.pageXOffset||b.scrollLeft,d.pageYOffset||b.scrollTop),c.x=a.left+b.x,c.y=a.top+b.y);c=c.y;return 2E3<c?0:1/(1+Math.exp(.001*c))};
var Ad=function(a,b){this.a=a;this.c=b};x(Ad,nd);var Bd=function(){this.a=[]};x(Bd,pd);p(Bd);Bd.prototype.c=function(a){var b=Y(this,a.getElementsByTagName("meta"));b.push(Cd(a));if(a=a?a.parentWindow||a.defaultView:window)a=a.getSelection().toString(),0<a.length&&b.push(new Ad(1,a));return b};
Bd.prototype.d=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:description"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "twitter:description":b=.8;break;case "description":b=.7;break;case "msapplication-tooltip":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=jd(c);a=document.createElement("div");a.innerHTML=c;c=a.textContent;c=c.trim();return 5<c.length?(1024<c.length&&(c=c.substring(0,1021)+"..."),
new Ad(b,c)):null};
var Cd=function(a){if(a.body){var b="",c="",d=0;a=a.body.innerText.replace(/(\r\n|\r|\n)/g,"\n");for(var e=a.split("\n"),f=0;f<e.length;++f){for(var b=e[f].replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),g=b.split(" "),k=g.length,l,q=l=0;q<b.length;++q)!/[^a-zA-Z]/.test(b.charAt(q))&&++l;if(q=64<=b.length&&8<=k&&l>=.4*b.length){for(var n=q=0;n<b.length;++n){var t=b.charAt(n);/[^a-zA-Z0-9]/.test(t)&&/[^\t\n\r ]/.test(t)&&++q}q=0<q}if(q&&24>=Dd(g))break;l>=.4*b.length&&k>d&&24>=Dd(g)&&(c=b,d=k); b=""}0==b.length&&20<c.length&&4<=d&&(b=c);a=a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"");return new Ad(.1,b||a.substring(0,1024))}return null},Dd=function(a){for(var b=0,c=0;c<a.length;++c)b=Math.max(a[c].length,b);return b};
var Ed=function(a,b){this.a=a;this.c=b};x(Ed,nd);var Fd=function(a){return a.c};var Gd=function(a,b,c){this.a=a;this.d=b;this.c=c};x(Gd,nd);var Hd=function(a,b,c,d){this.d=a;this.a=b;this.c=c;this.e=d};Hd.prototype.getTitle=function(){return this.d};var Id=function(){this.a=[]};x(Id,pd);p(Id);Id.prototype.c=function(a){var b=Y(this,a.getElementsByTagName("meta")).concat(Y(this,a.getElementsByTagName("title"))),c=Y(this,a.getElementsByTagName("h1"));0<c.length?1==c.length&&(b=za(b,c)):(c=Y(this,a.getElementsByTagName("h2")),0<c.length?1==c.length&&(b=za(b,c)):(c=Y(this,a.getElementsByTagName("h3")),0<c.length&&1==c.length&&(b=za(b,c))));a.title&&b.push(new Ed(1,a.title));b.push(new Ed(.1,a.documentURI));return b};
Id.prototype.d=function(a){var b=0,c="";switch(a.tagName.toLowerCase()){case "title":b=.5;c=dd(a);break;case "h1":b=.4;c=dd(a);break;case "h2":b=.3;c=dd(a);break;case "h3":b=.2;c=dd(a);break;case "meta":var d=a.getAttribute("name"),e=a.getAttribute("property");if(e&&"og:title"==e.toLowerCase())b=.9;else if(d)switch(d.toLowerCase()){case "application-name":b=.8;break;case "twitter:title":b=.7;break;case "title":b=.6}0<b&&(c=a.getAttribute("content")||"")}c=jd(c.trim());return 1<c.length?new Ed(b,c): null};
var Jd=function(){this.a=[]};x(Jd,pd);p(Jd);Jd.prototype.d=function(a){switch(a.tagName.toLowerCase()){case "meta":var b;t:{if("og:video"==A(a.getAttribute("property")).toLowerCase()){b=a.getAttribute("content");var c=ra(a.getAttribute("data-google-stars-video-width"));a=ra(a.getAttribute("data-google-stars-video-height"));if(b&&0<c&&0<a){b=new Gd(1,b,new U(c,a));break t}}b=null}return b}return null};
var Kd=function(a,b,c,d){this.d=a||Id.w();this.c=b||Bd.w();this.a=c||td.w();this.e=d||Jd.w()};p(Kd);var Ld=function(){var a=Kd.w(),b=document,c=qd(a.d,b),d=qd(a.c,b),e=a.a.c(b),a=qd(a.e,b);Ba(e,function(a){return a.c});return new Hd(c,d,e,a)};var Md=function(){md.call(this);this.a=null;this.k=new ld(this);ka(this,ia(la,this.k))};x(Md,md);var Nd=R("image.collections.extension.ContentController");Md.prototype.d=function(a){Md.K.d.call(this,a);this.k.listen(chrome.runtime.onMessage,this.W)};
Md.prototype.W=function(a,b,c){c({received:"true"});switch(a.type){case "collect_page":if(null===this.a){b=a.clipId;c=a.userId;a=new Pa;F(a,1,b);F(a,2,c);b=new Ua;H(b,1,a);a=ja();F(b,7,a);F(b,8,a);this.a=new W(b);b=document.documentURI;/\.(jpg|jpeg|png|gif|bmp|svg|tiff)$/i.test(b)?Tc(this.a,1):Tc(this.a,2);a=new Fb;try{Bb(b)}catch(d){b=encodeURI(b)}try{Bb(b)}catch(e){b=""}F(a.a,3,b);b=this.a;b.m=a;H(b.a,6,a.a);Od(this,!0)}else Nd&&Nd.log(Ob,"Clip is already being created",void 0);break;case "get_salient_images":Od(this,
!1);break;default:Nd&&Nd.log(Nb,"Invalid message type: "+a.type,void 0)}};var Od=function(a,b){var c=w(a.G,a,b);Ac(a.m,a.g,"dom_initialized",c,void 0);a.A("initialize_dom")};
Md.prototype.G=function(a){var b=Ld(),c=b.c;c.sort(od||Ca);for(var d=[],e=null,f=0;f<c.length;f++){var g=e=new Nc,k=c[f].c;g.c=null;try{var l=I(g.a);F(l,1,k);g.c=new P(A(Oa(I(g.a))))}catch(q){k=I(g.a),F(k,1,void 0),k=I(g.a),F(k,2,void 0),k=I(g.a),F(k,3,void 0)}g.c&&E(g.a,6)&&F(g.a,6,!1);var n=c[f].d;if(n){var g=e,k=n.width,n=n.height,t=I(g.a);F(t,2,k);g=I(g.a);F(g,3,n)}d.unshift(e.i())}if(a){!Sc(this.a)&&e&&(a=this.a,c=e,a.d=c,H(a.a,5,c.a),c=ja(),F(a.a,8,c));a=V(this.a);!a.getTitle()&&b.getTitle()&&
a.setTitle(Fd(b.getTitle()));!A(E(a.a,2))&&b.a&&F(a.a,2,b.a.c);if(a=b.e)Tc(this.a,4),b=new Pc,F(b.a,1,a.d),c=a.c.height,F(b.a,2,a.c.width),F(b.a,3,c),a=this.a,a.k=b,H(a.a,10,b.a);chrome.runtime.sendMessage({type:"created_clip",clipData:this.a.i(),images:d});this.a=null}else chrome.runtime.sendMessage({type:"salient_images_found",images:d})};
var Z=function(){md.call(this);this.a=0;this.k=-1};x(Z,md);var Pd=R("image.collections.extension.DomController");Z.prototype.d=function(a){Z.K.d.call(this,a);this.m.listen(a,"initialize_dom",this.W)};
Z.prototype.W=function(){if(0==this.a){var a=document,b=a.getElementsByTagName("meta"),a=a.getElementsByTagName("link");this.a=b.length+a.length;if(0<this.a){wa(b,this.ga,this);wa(a,this.fa,this);b=w(this.A,this,"dom_initialized");if(!ba(b))if(b&&"function"==typeof b.handleEvent)b=w(b.handleEvent,b);else throw Error("Invalid listener argument");this.k=m.setTimeout(b,5E3)}else this.A("dom_initialized")}};
Z.prototype.ga=function(a){var b="";if(a.hasAttribute("property"))switch(a.getAttribute("property").toLowerCase()){case "og:image":var b=a.getAttribute("content"),c=Yc(Zc(a)),d=Qd(c,"og:image:width"),c=Qd(c,"og:image:height");0<d&&0<c&&(a.setAttribute("data-google-stars-image-width",d),a.setAttribute("data-google-stars-image-height",c));break;case "og:video":c=Yc(Zc(a)),d=Qd(c,"og:video:width"),c=Qd(c,"og:video:height"),0<d&&0<c&&(a.setAttribute("data-google-stars-video-width",d),a.setAttribute("data-google-stars-video-height",
c))}else if(a.hasAttribute("name"))switch(a.getAttribute("name").toLowerCase()){case "msapplication-tileimage":case "twitter:image":b=a.getAttribute("content")}else if(a.hasAttribute("itemprop"))switch(a.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":b=a.getAttribute("href")||a.getAttribute("content")}Rd(this,b,a)};
Z.prototype.fa=function(a){var b="";if(a.hasAttribute("rel"))switch(a.getAttribute("rel").toLowerCase()){case "apple-touch-icon-precomposed":case "apple-touch-icon":case "image_src":b=a.getAttribute("href")}else if(a.hasAttribute("itemprop"))switch(a.getAttribute("itemprop").toLowerCase()){case "thumbnailurl":b=a.getAttribute("href")||a.getAttribute("content")}Rd(this,b,a)};
var Qd=function(a,b){for(var c=0;c<a.length;++c){var d=a[c];if(d.hasAttribute("property")&&d.getAttribute("property").toLowerCase()==b&&d.hasAttribute("content"))return d.getAttribute("content")}return""},Rd=function(a,b,c){if(!b||c.hasAttribute("data-google-stars-image-width")&&c.hasAttribute("data-google-stars-image-height"))Sd(a);else{var d=w(a.ha,a,c);c=new Image;d=w(a.G,a,d);Ac(a.m,c,["load","error"],d,void 0);c.src=b}};
Z.prototype.G=function(a,b){var c=b.target;"load"==b.type?a(c.naturalWidth,c.naturalHeight):Pd&&Pd.log(Ob,"Failed to load image "+c.src,void 0);Sd(this)};var Sd=function(a){0==--a.a&&(-1!=a.k&&(m.clearTimeout(a.k),a.k=-1),a.A("dom_initialized"))};Z.prototype.ha=function(a,b,c){a.setAttribute("data-google-stars-image-width",b);a.setAttribute("data-google-stars-image-height",c)};
var Td=function(){this.a=ja()},Ud=new Td;Td.prototype.set=function(a){this.a=a};Td.prototype.get=function(){return this.a};var Vd=function(a){this.e=a||"";this.g=Ud};Vd.prototype.a=!0;Vd.prototype.c=!0;Vd.prototype.d=!1;var Wd=function(a){return 10>a?"0"+a:String(a)},Xd=function(a,b){var c=(a.d-b)/1E3,d=c.toFixed(3),e=0;if(1>c)e=2;else for(;100>c;)e++,c*=10;for(;0<e--;)d=" "+d;return d},Yd=function(a){Vd.call(this,a)};x(Yd,Vd);
var Zd=function(){w(this.e,this);this.a=new Yd;this.a.c=!1;this.a.d=!1;this.c=this.a.a=!1;this.d="";this.g={}};
Zd.prototype.e=function(a){if(!this.g[a.c]){var b;b=this.a;var c=[];c.push(b.e," ");if(b.c){var d=new Date(a.d);c.push("[",Wd(d.getFullYear()-2E3)+Wd(d.getMonth()+1)+Wd(d.getDate())+" "+Wd(d.getHours())+":"+Wd(d.getMinutes())+":"+Wd(d.getSeconds())+"."+Wd(Math.floor(d.getMilliseconds()/10)),"] ")}c.push("[",Xd(a,b.g.get()),"s] ");c.push("[",a.c,"] ");c.push(a.getMessage());b.d&&(d=a.a)&&c.push("\n",d instanceof Error?d.message:d.toString());b.a&&c.push("\n");b=c.join("");if(c=$d)switch(a.e){case Mb:ae(c, "info",b);break;case Nb:ae(c,"error",b);break;case Ob:ae(c,"warn",b);break;default:ae(c,"debug",b)}else this.d+=b}};var $d=m.console,ae=function(a,b,c){if(a[b])a[b](c);else a.log(c)};
var be=function(){T.call(this);this.d=new Z;ka(this,ia(la,this.d));this.a=new Md;ka(this,ia(la,this.a))};x(be,T);p(be);var ce=new Zd;0!=ce.c&&(Ub(),ce.c=!1);var de=R("image.collections.extension.Content"),ee=be.w();de&&de.log(Pb,"Initializing extension content",void 0);ee.d.d(ee);ee.a.d(ee);window.full_script_injected=!0;

}catch(e){_DumpException(e)}
// Google Inc.
