try{
'use strict';var f=this,g=function(a){a.h=function(){return a.n?a.n:a.n=new a}},aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&
"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},l=function(a){return"function"==aa(a)},ba=function(a,b,c){return a.call.apply(a.bind,arguments)},ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,
c)}}return function(){return a.apply(b,arguments)}},m=function(a,b,c){m=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return m.apply(null,arguments)},da=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},ea=Date.now||function(){return+new Date};
var n=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},u=function(a,b){return a<b?-1:a>b?1:0};var w;n:{var x=f.navigator;if(x){var y=x.userAgent;if(y){w=y;break n}}w=""};var fa=-1!=w.indexOf("Opera")||-1!=w.indexOf("OPR"),z=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),A=-1!=w.indexOf("Gecko")&&-1==w.toLowerCase().indexOf("webkit")&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE")),ga=-1!=w.toLowerCase().indexOf("webkit"),B=function(){var a=f.document;return a?a.documentMode:void 0},C=function(){var a="",b;if(fa&&f.opera)return a=f.opera.version,l(a)?a():a;A?b=/rv\:([^\);]+)(\)|;)/:z?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:ga&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(w))?
a[1]:"");return z&&(b=B(),b>parseFloat(a))?String(b):a}(),D={},E=function(a){if(!D[a]){for(var b=0,c=n(String(C)).split("."),d=n(String(a)).split("."),e=Math.max(c.length,d.length),h=0;0==b&&h<e;h++){var k=c[h]||"",p=d[h]||"",v=/(\d*)(\D*)/g,q=/(\d*)(\D*)/g;do{var r=v.exec(k)||["","",""],t=q.exec(p)||["","",""];if(0==r[0].length&&0==t[0].length)break;b=u(0==r[1].length?0:parseInt(r[1],10),0==t[1].length?0:parseInt(t[1],10))||u(0==r[2].length,0==t[2].length)||u(r[2],t[2])}while(0==b)}D[a]=0<=b}},F= f.document,ha=F&&z?B()||("CSS1Compat"==F.compatMode?parseInt(C,10):5):void 0;
var G;if(!(G=!A&&!z)){var H;if(H=z)H=z&&9<=ha;G=H}G||A&&E("1.9.1");z&&E("9");var I=function(a){a()},ia=function(a){var b=document.body;b&&a&&I(function(){b.appendChild(a)})},ja=function(a,b){I(function(){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{for(var c;c=a.firstChild;)a.removeChild(c);a.appendChild((9==a.nodeType?a:a.ownerDocument||a.document).createTextNode(String(b)))}})};
var J=function(a){f.setTimeout(function(){throw a;},0)},K,ka=function(){var a=f.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&-1==w.indexOf("Presto")&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+
b.location.host,a=m(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&-1==w.indexOf("Trident")&&-1==w.indexOf("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.i;c.i=null;a()}};return function(a){d.next={i:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in
document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){f.setTimeout(a,0)}};
var O=function(a,b){L||la();M||(L(),M=!0);N.push(new ma(a,b))},L,la=function(){if(f.Promise&&f.Promise.resolve){var a=f.Promise.resolve();L=function(){a.then(P)}}else L=function(){var a=P;!l(f.setImmediate)||f.Window&&f.Window.prototype.setImmediate==f.setImmediate?(K||(K=ka()),K(a)):f.setImmediate(a)}},M=!1,N=[],P=function(){for(;N.length;){var a=N;N=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.c)}catch(d){J(d)}}}M=!1},ma=function(a,b){this.a=a;this.c=b};
var R=function(a,b){this.c=0;this.l=void 0;this.a=this.k=null;this.d=this.g=!1;try{var c=this;a.call(b,function(a){Q(c,2,a)},function(a){Q(c,3,a)})}catch(d){Q(this,3,d)}},na=function(a){return new R(function(b,c){var d=a.length,e=[];if(d)for(var h=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},p=0,v;v=a[p];p++)v.then(da(h,p),k);else b(e)})};R.prototype.then=function(a,b,c){return oa(this,l(a)?a:null,l(b)?b:null,c)};R.prototype.then=R.prototype.then;R.prototype.$goog_Thenable=!0;
var pa=function(a,b){a.a&&a.a.length||2!=a.c&&3!=a.c||S(a);a.a||(a.a=[]);a.a.push(b)},oa=function(a,b,c,d){var e={e:null,p:null,s:null};e.e=new R(function(a,k){e.p=b?function(c){try{var e=b.call(d,c);a(e)}catch(q){k(q)}}:a;e.s=c?function(b){try{var e=c.call(d,b);a(e)}catch(q){k(q)}}:k});e.e.k=a;pa(a,e);return e.e};R.prototype.m=function(a){this.c=0;Q(this,2,a)};R.prototype.o=function(a){this.c=0;Q(this,3,a)};
var Q=function(a,b,c){if(0==a.c){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{var d;if(c)try{d=!!c.$goog_Thenable}catch(e){d=!1}else d=!1;if(d){a.c=1;c.then(a.m,a.o,a);return}d=typeof c;if("object"==d&&null!=c||"function"==d)try{var h=c.then;if(l(h)){qa(a,c,h);return}}catch(k){b=3,c=k}}a.l=c;a.c=b;S(a);3!=b||ra(a,c)}},qa=function(a,b,c){a.c=1;var d=!1,e=function(b){d||(d=!0,a.m(b))},h=function(b){d||(d=!0,a.o(b))};try{c.call(b,e,h)}catch(k){h(k)}},S=function(a){a.g||(a.g=!0,
O(a.v,a))};R.prototype.v=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++){var c=a[b],d=this.l;if(2==this.c)c.p(d);else{if(c.e)for(var e=void 0,e=this;e&&e.d;e=e.k)e.d=!1;c.s(d)}}}this.g=!1};var ra=function(a,b){a.d=!0;O(function(){a.d&&sa.call(null,b)})},sa=J;
var T=function(){this.c={};this.a={}};g(T);var U=function(a,b,c,d,e){"number"==typeof e||ta++;d||ea();this.c=b;delete this.a};U.prototype.a=null;var ta=0;U.prototype.getMessage=function(){return this.c};var V=function(){this.c=this.d=this.a=null},W=function(a,b){this.name=a;this.value=b};W.prototype.toString=function(){return this.name};var ua=new W("SEVERE",1E3),va=new W("CONFIG",700);V.prototype.getChildren=function(){this.c||(this.c={});return this.c};var wa=function(a){return a.d?a.d:a.a?wa(a.a):null};
V.prototype.log=function(a,b,c){if(a.value>=wa(this).value)for(l(b)&&(b=b()),a=new U(0,String(b)),c&&(a.a=c),c="log:"+a.getMessage(),f.console&&(f.console.timeStamp?f.console.timeStamp(c):f.console.markTimeline&&f.console.markTimeline(c)),f.msWriteProfilerMark&&f.msWriteProfilerMark(c),c=this;c;)c=c.a};var X={},Y=null,xa=function(a){Y||(Y=new V,X[""]=Y,Y.d=va);var b;if(!(b=X[a])){b=new V;var c=a.lastIndexOf("."),d=a.substr(c+1),c=xa(a.substr(0,c));c.getChildren()[d]=b;b.a=c;X[a]=b}return b};
var Z;Z=xa("image.collections.extension.Promises");var sa=function(a){Z&&Z.log(ua,a.toString(),void 0)},ya=function(a,b,c){return function(d){var e=chrome.runtime.lastError;e?(d=T.h(),a&&(d.a[a]=(d.a[a]||0)+1),c(e.message||"Unknown Chrome API error")):(e=T.h(),a&&(e.c[a]=(e.c[a]||0)+1),b(d))}},za=function(a,b){return new R(function(c,d){chrome.tabs.sendMessage(a,b,ya("chrome.tabs.sendMessage",c,d))})},Aa=function(){return new R(function(a,b){chrome.tabs.getCurrent(ya("chrome.tabs.getCurrent",a,b))})};
var Ba=function(){};g(Ba);(function(){Ba.h();var a={type:"get_log_history"},b={type:"get_chrome_api_logs"};Aa().then(function(c){c=c.openerTabId;return na([za(c,a),za(c,b)])}).then(function(a){var b;b=document.createElement("pre");ja(b,a[0]+"\nChrome API calls:\n"+a[1]);ia(b)})})();

}catch(e){_DumpException(e)}
// Google Inc.
