try{
'use strict';var h=this,l=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},aa=function(a,b,c){return a.call.apply(a.bind,arguments)},ba=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},m=function(a,b,c){m=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?
aa:ba;return m.apply(null,arguments)},ca=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},da=Date.now||function(){return+new Date},n=function(a,b){function c(){}c.prototype=b.prototype;a.s=b.prototype;a.prototype=new c;a.G=function(a,c,f){for(var k=Array(arguments.length-2),g=2;g<arguments.length;g++)k[g-2]=arguments[g];return b.prototype[c].apply(a,k)}};
var ea=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},p=function(a,b){return a<b?-1:a>b?1:0};var q=Array.prototype,fa=q.indexOf?function(a,b,c){return q.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if("string"==typeof a)return"string"==typeof b&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
var r;t:{var ga=h.navigator;if(ga){var ha=ga.userAgent;if(ha){r=ha;break t}}r=""};var ia=-1!=r.indexOf("Opera")||-1!=r.indexOf("OPR"),t=-1!=r.indexOf("Trident")||-1!=r.indexOf("MSIE"),u=-1!=r.indexOf("Gecko")&&-1==r.toLowerCase().indexOf("webkit")&&!(-1!=r.indexOf("Trident")||-1!=r.indexOf("MSIE")),v=-1!=r.toLowerCase().indexOf("webkit"),ja=function(){var a=h.document;return a?a.documentMode:void 0},ka=function(){var a="",b;if(ia&&h.opera)return a=h.opera.version,"function"==l(a)?a():a;u?b=/rv\:([^\);]+)(\)|;)/:t?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:v&&(b=/WebKit\/(\S+)/);b&&(a=
(a=b.exec(r))?a[1]:"");return t&&(b=ja(),b>parseFloat(a))?String(b):a}(),la={},w=function(a){var b;if(!(b=la[a])){b=0;for(var c=ea(String(ka)).split("."),d=ea(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var k=c[f]||"",g=d[f]||"",D=/(\d*)(\D*)/g,La=/(\d*)(\D*)/g;do{var E=D.exec(k)||["","",""],F=La.exec(g)||["","",""];if(0==E[0].length&&0==F[0].length)break;b=p(0==E[1].length?0:parseInt(E[1],10),0==F[1].length?0:parseInt(F[1],10))||p(0==E[2].length,0==F[2].length)||p(E[2], F[2])}while(0==b)}b=la[a]=0<=b}return b},ma=h.document,na=ma&&t?ja()||("CSS1Compat"==ma.compatMode?parseInt(ka,10):5):void 0;
var x=function(a,b,c,d,e){"number"==typeof e||oa++;this.d=d||da();this.e=a;this.g=b;this.c=c;delete this.a};x.prototype.a=null;var oa=0;x.prototype.getMessage=function(){return this.g};var y=function(a){this.e=a;this.c=this.d=this.a=null},z=function(a,b){this.name=a;this.value=b};z.prototype.toString=function(){return this.name};var pa=new z("SHOUT",1200),qa=new z("SEVERE",1E3),ra=new z("WARNING",900),sa=new z("INFO",800),ta=new z("CONFIG",700);y.prototype.getChildren=function(){this.c||(this.c={});return this.c};var ua=function(a){return a.d?a.d:a.a?ua(a.a):null};
y.prototype.log=function(a,b,c){if(a.value>=ua(this).value)for("function"==l(b)&&(b=b()),a=new x(a,String(b),this.e),c&&(a.a=c),c="log:"+a.getMessage(),h.console&&(h.console.timeStamp?h.console.timeStamp(c):h.console.markTimeline&&h.console.markTimeline(c)),h.msWriteProfilerMark&&h.msWriteProfilerMark(c),c=this;c;)c=c.a}; var A={},B=null,va=function(){B||(B=new y(""),A[""]=B,B.d=ta)},C=function(a){va();var b;if(!(b=A[a])){b=new y(a);var c=a.lastIndexOf("."),d=a.substr(c+1),c=C(a.substr(0,c));c.getChildren()[d]=b;b.a=c;A[a]=b}return b};
C("image.collections.extension.Promises");var G=function(a){this.a=a},wa={"stars-gws":"https://www.google.com","stars-last-import-time":0};G.prototype.get=function(a,b){this.a.get(a,m(this.c,this,a,b))};G.prototype.c=function(a,b,c){null!=c||(c={});for(var d=0;d<a.length;++d){var e=a[d];e in c||(c[e]=wa[e])}b(c)};G.prototype.set=function(a){this.a.set(a)};
var H=function(){this.a=da()},xa=new H;H.prototype.set=function(a){this.a=a};H.prototype.get=function(){return this.a};var I=function(a){this.e=a||"";this.g=xa};I.prototype.a=!0;I.prototype.c=!0;I.prototype.d=!1;var J=function(a){return 10>a?"0"+a:String(a)},ya=function(a,b){var c=(a.d-b)/1E3,d=c.toFixed(3),e=0;if(1>c)e=2;else for(;100>c;)e++,c*=10;for(;0<e--;)d=" "+d;return d},za=function(a){I.call(this,a)};n(za,I);
var Aa=function(){m(this.e,this);this.a=new za;this.a.c=!1;this.a.d=!1;this.c=this.a.a=!1;this.d="";this.g={}};
Aa.prototype.e=function(a){if(!this.g[a.c]){var b;b=this.a;var c=[];c.push(b.e," ");if(b.c){var d=new Date(a.d);c.push("[",J(d.getFullYear()-2E3)+J(d.getMonth()+1)+J(d.getDate())+" "+J(d.getHours())+":"+J(d.getMinutes())+":"+J(d.getSeconds())+"."+J(Math.floor(d.getMilliseconds()/10)),"] ")}c.push("[",ya(a,b.g.get()),"s] ");c.push("[",a.c,"] ");c.push(a.getMessage());b.d&&(d=a.a)&&c.push("\n",d instanceof Error?d.message:d.toString());b.a&&c.push("\n");b=c.join("");if(c=Ba)switch(a.e){case pa:K(c, "info",b);break;case qa:K(c,"error",b);break;case ra:K(c,"warn",b);break;default:K(c,"debug",b)}else this.d+=b}};var Ba=h.console,K=function(a,b,c){if(a[b])a[b](c);else a.log(c)};
var L=function(){this.d=this.d;this.a=this.a};L.prototype.d=!1;L.prototype.v=function(){this.d||(this.d=!0,this.c())};L.prototype.c=function(){if(this.a)for(;this.a.length;)this.a.shift()()};var Ca=function(a){a&&"function"==typeof a.v&&a.v()};!u&&!t||t&&t&&9<=na||u&&w("1.9.1");t&&w("9");var Da=!t||t&&9<=na,Ea=t&&!w("9");!v||w("528");u&&w("1.9b")||t&&w("8")||ia&&w("9.5")||v&&w("528");u&&!w("8")||t&&w("9");var M=function(a,b){this.type=a;this.c=this.target=b};M.prototype.d=function(){};var N=function(a){N[" "](a);return a};N[" "]=function(){};var O=function(a,b){M.call(this,a?a.type:"");this.c=this.target=null;this.p=this.o=0;this.a=this.state=null;if(a){this.a=a;this.type=a.type;this.target=a.target||a.srcElement;this.c=b;var c=a.relatedTarget;if(c&&u)try{N(c.nodeName)}catch(d){}Object.defineProperties?Object.defineProperties(this,{o:{configurable:!0,enumerable:!0,get:this.e,set:this.k},p:{configurable:!0,enumerable:!0,get:this.g,set:this.l}}):(this.o=this.e(),this.p=this.g());this.state=a.state;a.defaultPrevented&&this.d()}};n(O,M);
O.prototype.d=function(){O.s.d.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Ea)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};O.prototype.e=function(){return v||void 0!==this.a.offsetX?this.a.offsetX:this.a.layerX};O.prototype.k=function(a){Object.defineProperties(this,{o:{writable:!0,enumerable:!0,configurable:!0,value:a}})};O.prototype.g=function(){return v||void 0!==this.a.offsetY?this.a.offsetY:this.a.layerY}; O.prototype.l=function(a){Object.defineProperties(this,{p:{writable:!0,enumerable:!0,configurable:!0,value:a}})};
var P="closure_listenable_"+(1E6*Math.random()|0),Fa=0;var Ga=function(a,b,c,d,e){this.i=a;this.proxy=null;this.src=b;this.type=c;this.n=!!d;this.a=e;this.w=++Fa;this.removed=this.m=!1},Q=function(a){a.removed=!0;a.i=null;a.proxy=null;a.src=null;a.a=null};var R=function(a){this.src=a;this.a={};this.c=0},Ha=function(a,b,c,d,e){var f=b.toString();b=a.a[f];b||(b=a.a[f]=[],a.c++);var k=S(b,c,d,e);-1<k?(a=b[k],a.m=!1):(a=new Ga(c,a.src,f,!!d,e),a.m=!1,b.push(a));return a};R.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=S(e,b,c,d);return-1<b?(Q(e[b]),q.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.c--),!0):!1};
var Ia=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=a.a[c],e=fa(d,b),f;(f=0<=e)&&q.splice.call(d,e,1);f&&(Q(b),0==a.a[c].length&&(delete a.a[c],a.c--));return f};R.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Q(d[e]);delete this.a[c];this.c--}return b}; var T=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=S(a,c,d,e));return-1<b?a[b]:null},S=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.i==b&&f.n==!!c&&f.a==d)return e}return-1};
var Ja="closure_lm_"+(1E6*Math.random()|0),Ka={},Ma=0,Na=function(a,b,c,d,e){if("array"==l(b)){for(var f=0;f<b.length;f++)Na(a,b[f],c,d,e);return null}c=Oa(c);if(a&&a[P])a=a.listen(b,c,d,e);else{if(!b)throw Error("Invalid event type");var f=!!d,k=U(a);k||(a[Ja]=k=new R(a));c=Ha(k,b,c,d,e);c.proxy||(d=Pa(),c.proxy=d,d.src=a,d.i=c,a.addEventListener?a.addEventListener(b.toString(),d,f):a.attachEvent(Qa(b.toString()),d),Ma++);a=c}return a},Pa=function(){var a=Ra,b=Da?function(c){return a.call(b.src,
b.i,c)}:function(c){c=a.call(b.src,b.i,c);if(!c)return c};return b},Sa=function(a,b,c,d,e){if("array"==l(b))for(var f=0;f<b.length;f++)Sa(a,b[f],c,d,e);else c=Oa(c),a&&a[P]?a.unlisten(b,c,d,e):a&&(a=U(a))&&(b=T(a,b,c,!!d,e))&&V(b)},V=function(a){if("number"==typeof a||!a||a.removed)return!1;var b=a.src;if(b&&b[P])return Ia(b.h,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.n):b.detachEvent&&b.detachEvent(Qa(c),d);Ma--;(c=U(b))?(Ia(c,a),0==c.c&&(c.src=null,b[Ja]=null)):
Q(a);return!0},Qa=function(a){return a in Ka?Ka[a]:Ka[a]="on"+a},Ua=function(a,b,c,d){var e=!0;if(a=U(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.n==c&&!f.removed&&(f=Ta(f,d),e=e&&!1!==f)}return e},Ta=function(a,b){var c=a.i,d=a.a||a.src;a.m&&V(a);return c.call(d,b)},Ra=function(a,b){if(a.removed)return!0;if(!Da){var c;if(!(c=b))t:{c=["window","event"];for(var d=h,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new O(e,this);d=!0;if(!(0>e.keyCode||
void 0!=e.returnValue)){t:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(k){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.c;f;f=f.parentNode)e.push(f);for(var f=a.type,g=e.length-1;0<=g;g--){c.c=e[g];var D=Ua(e[g],f,!0,c),d=d&&D}for(g=0;g<e.length;g++)c.c=e[g],D=Ua(e[g],f,!1,c),d=d&&D}return d}return Ta(a,new O(b,this))},U=function(a){a=a[Ja];return a instanceof R?a:null},Va="__closure_events_fn_"+(1E9*Math.random()>>>0),Oa=function(a){if("function"==l(a))return a;a[Va]|| (a[Va]=function(b){return a.handleEvent(b)});return a[Va]};
var W=function(a){L.call(this);this.g=a;this.e={}};n(W,L);var Wa=[];W.prototype.listen=function(a,b,c,d){"array"!=l(b)&&(b&&(Wa[0]=b.toString()),b=Wa);for(var e=0;e<b.length;e++){var f=Na(a,b[e],c||this.handleEvent,d||!1,this.g||this);if(!f)break;this.e[f.w]=f}return this};
W.prototype.unlisten=function(a,b,c,d,e){if("array"==l(b))for(var f=0;f<b.length;f++)this.unlisten(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.g||this,c=Oa(c),d=!!d,b=a&&a[P]?T(a.h,String(b),c,d,e):a?(a=U(a))?T(a,b,c,d,e):null:null,b&&(V(b),delete this.e[b.w]);return this};W.prototype.removeAll=function(){var a=this.e,b=V,c;for(c in a)b.call(void 0,a[c],c,a);this.e={}};W.prototype.c=function(){W.s.c.call(this);this.removeAll()}; W.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};
var X=function(){L.call(this);this.h=new R(this)};n(X,L);X.prototype[P]=!0;X.prototype.addEventListener=function(a,b,c,d){Na(this,a,b,c,d)};X.prototype.removeEventListener=function(a,b,c,d){Sa(this,a,b,c,d)};X.prototype.c=function(){X.s.c.call(this);this.h&&this.h.removeAll(void 0)};X.prototype.listen=function(a,b,c,d){return Ha(this.h,String(a),b,c,d)};X.prototype.unlisten=function(a,b,c,d){return this.h.remove(String(a),b,c,d)};
var Y=function(){X.call(this);var a=document;this.k=a.getElementById("gws");this.e=a.getElementById("save_and_exit");this.e.disabled=!0;this.l=new G(chrome.storage.sync);this.g=new W(this);a=ca(Ca,this.g);this.d?a.call(void 0):(this.a||(this.a=[]),this.a.push(a))};n(Y,X);Y.c=function(){return Y.a?Y.a:Y.a=new Y};var Xa=new Aa;0!=Xa.c&&(va(),Xa.c=!1);var Ya=C("image.collections.extension.Options");Y.prototype.C=function(a){this.k.value=a["stars-gws"]};
Y.prototype.B=function(){this.l.set({"stars-gws":this.k.value});this.e.disabled=!0;chrome.runtime.reload()};Y.prototype.A=function(){this.e.disabled=!1};var Z=Y.c();Ya&&Ya.log(sa,"Initializing extension options",void 0);Z.g.listen(Z.e,"click",Z.B).listen(document.body,"input",Z.A);var Za={D:"stars-gws",F:"stars-last-import-time"},$a=[],ab=0,bb;for(bb in Za)$a[ab++]=Za[bb];Z.l.get($a,m(Z.C,Z));

}catch(e){_DumpException(e)}
// Google Inc.
