var D=!0;
Registry.require(["pingpong","crcrc","layout/default/htmlutil","i18n","layout/default/layout_helper"],function(){var z=Registry.prepare(),n=Registry.get("crcrc").cr,h=Registry.get("crcrc").crc,q=Registry.get("layout/default/htmlutil"),k=Registry.get("i18n"),t=Registry.get("layout"),u=Registry.get("layout/default/layout_helper"),r=u.images;t.render(function(){var p={};u.addStyle();u.addFont();var t=function(d,a){var c=[];if(a.sub_menu_item){var b=h("table","actiontable","actiontable-"+a.name);w(b,
a.items);c.push(b)}else if(b=null,a.image?b=q.createImage(r.get(a.image),a.name,a.id,null,""):a.enabler&&(b=q.createImage(chrome.extension.getURL(p.enabled?"/layout/default/images/button_ok.png":"/layout/default/images/cancel.png"),a.name,a.uuid,null,"")),b&&c.push(b),a.url||a.urls){for(var b=n("span",a.name,a.id,"urls"),e=a.urls||[a],f=0;f<e.length;f++){var g=e[f],v=document.createElement("span");v.textContent=g.name;var s=a.urls?v:b;s.url=g.url;s.newtab=g.newtab;s.addEventListener("click",function(){A(this.url,
this.newtab)});$(s).addClass("clickable");b.appendChild(v);f<e.length-1&&(g=document.createElement("span"),g.textContent=" | ",b.appendChild(g))}c.push(b);a.tamperfire&&function(){var b=function(b,e){c&&1<c.length&&(c[1].textContent=e?e:c[1].textContent.replace("?",Number(b)));c[0]&&c[0].setAttribute("src",r.get(a.doneImage))};a.tabid&&B(a.tabid,b)}()}else if(a.menucmd){var l=document.createElement("span");d.id=a.id;e=function(){C(this.id,window.close)};d.addEventListener("click",e);$(d).addClass("clickable");
l.textContent=a.name;a.accessKey&&(b=a.accessKey[0].toUpperCase(),E(b,e,d)?(e=RegExp(b,"i"),f=l.textContent.search(e),g=[],-1==f&&(l.textContent+=" ("+b+")",f=l.textContent.search(e)),g.push({text:l.textContent.substr(0,f)}),g.push({text:l.textContent.substr(f,1),class:"underlined"}),g.push({text:l.textContent.substr(f+1)}),l.textContent="",g.forEach(function(b){var e=h("span",b.class||"",a.id,b);e.textContent=b.text;l.appendChild(e)})):console.warn("Registering keyboard shortcut for '"+a.name+"' failed"));
c.push(l)}else if(a.button)b=h("span",a.display||"",a.name,a.id,"bu",!0),b.textContent=a.name,d.key=a.id,d.warning=a.warning,d.reload=a.reload,d.addEventListener("click",function(){var a=!0;this.warning&&(a=F(this.warning));a&&G(this.key,{reload:this.reload})}),$(d).addClass("clickable"),c.push(b);else if(a.userscript||a.user_agent){var b=n("span",a.name,a.uuid,"ai"),m;a.uuid&&(f=a.blacklisted?"enabler_warning":a.enabled?"enabler_enabled":"enabler_disabled",g=a.blacklisted?k.getMessage("This_script_is_blacklisted_"):
a.enabled?k.getMessage("Enabled"):k.getMessage("Disabled"),e=function(a){a&&a.button&2||a.button&1||a.ctrlKey?(window.open(chrome.extension.getURL("options.html")+"#open="+this.key),a.stopPropagation()):H(this.uuid,"enabled",!this.oldvalue)},f=q.createEnabler(f,a.uuid,"enabled","enabled",g,e,0<a.position?10>a.position?" "+a.position:a.position:null),f.oldvalue=a.enabled,c.push(f),b.uuid=a.uuid,b.oldvalue=a.enabled,b.key=a.uuid,b.addEventListener("click",e),e=" clickable",a.blacklisted&&(e+=" crossedout",
d.setAttribute("title",k.getMessage("This_script_is_blacklisted_"))),$(d).addClass(e),e=[],a.nnew||a.system||!a.origin||(f=q.createImage(r.get("flag"),"",a.uuid,"issue",k.getMessage("Report_an_issue_to_the_script_hoster_"),function(){x(a.uuid,"hoster")}),e.push(f)),a.nnew||a.system||!a.support||(f=q.createImage(r.get("bug"),"",a.uuid,"bug",k.getMessage("Report_a_bug"),function(){x(a.uuid,"author")}),e.push(f)),e.length&&(m=h("div","actionbuttons",a.uuid,"actions"),e.forEach(function(a){m.appendChild(a)})));
b.textContent=k.getTranslation(a,"name");c.push(b);m&&c.push(m)}else b=n("span",a.name,a.id,"ai"),b.textContent=a.name,c.push(b);return c},w=function(d,a,c){for(var b in a){var e=a[b];if(d||c[e.pos]){var f=d||c[e.pos],g=f?n("tr",e.name,e.uuid||e.id,"outer"):null,h=t(g,e);if(h&&h.length)for(f.appendChild(g),b=0;f=h[b];b++){var k=b==h.length-1?3-b:0,l=n("td","actiontd",e.name,e.uuid||e.id,b);0<k&&l.setAttribute("colspan",k);f&&l.appendChild(f);g.appendChild(l)}}else console.warn("Warn(cAm): unknown pos "+
e.pos)}},y=function(d,a){var c=document.getElementById("action"),b=c.parentNode;b.removeChild(c);c=n("span");c.setAttribute("id","action");b.appendChild(c);b=h("table","actionlayout","actionlayout");c.appendChild(b);var e=h("tr","actionpostr","hor"),c=h("td","actionpostd","hor_west");e.appendChild(c);b.appendChild(e);2===z.ACTIONMENU.COLUMNS&&p.enabled?(b=h("td","actionpostd","hor_east"),e.appendChild(b)):b=c;var e=h("table","actionregion","top"),f=h("table","actionregion","right"),g=h("table","actionregion",
"left"),k=h("table","actionregion","bottom");c.appendChild(e);b.appendChild(f);c.appendChild(g);c.appendChild(k);var m={top:e,left:g,right:f,bottom:k};window.setTimeout(function(){w(null,d,m)},1)},A=function(d,a){try{var c=function(b){chrome.tabs.sendMessage(b.id,{method:"loadUrl",url:d,newtab:a},function(a){})};a?sendMessage({method:"newTab",url:d},function(a){}):chrome.tabs.getSelected(null,c)}catch(b){console.warn("lU:",b)}},F=function(d){var a=confirm(d.msg),c={};a&&d.ok?c=d.ok:!a&&d.cancel&&
(c=d.cancel);if(d.ok||d.cancel)a=!0;c.url&&sendMessage({method:"newTab",url:c.url},function(a){});return a},x=function(d,a,c){try{sendMessage({method:"reportAnIssue",uuid:d,to:a},function(a){c&&c()})}catch(b){console.warn("raI:",b)}},G=function(d,a){try{sendMessage({method:"buttonPress",name:d},function(b){a.reload&&window.location.reload()})}catch(c){console.warn("rSU:",c)}},m={},I=function(d,a,c){document.body.addEventListener("keydown",function(a){D&&console.log("MenuCmdKeyListener: check event",
a);if(!(a.altKey||a.ctrlKey||a.shiftKey))for(var e in m)if(m.hasOwnProperty(e)){var c=m[e];c&&a.keyCode==c.key&&(D&&console.log("MenuCmdKeyListener: ... found",a.keyCode,String.fromCharCode(a.keyCode)),c.cb.apply(c.elem||window,[]))}},!1)},E=function(d,a,c){D&&console.log("MenuCmdKeyListener: register accessKey "+d);d=d.charCodeAt(0);if(m[d])return D&&console.log("MenuCmdKeyListener: ...failed!"),!1;m[d]={key:d,cb:a,elem:c};return!0},C=function(d,a){try{sendMessage({method:"execMenuCmd",id:d},function(b){a&&
a()})}catch(c){console.warn("Error(eMC):",c)}},B=function(d,a){try{sendMessage({method:"getFireItems",countonly:!0,tabid:d},function(b){var c=null;if(b.progress){(c=b.progress.action+"... ")&&""!=c||(c="");var d="";b.progress.state&&b.progress.state.of&&(d=" "+Math.round(100*b.progress.state.n/b.progress.state.of)+"%");c=""!=c||""!=d?c+d:null}a(b.cnt,c)})}catch(c){console.warn("Error(gFI):",c)}},H=function(d,a,c){try{d={method:"modifyScriptOptions",uuid:d},a&&""!=a&&(d[a]=c),sendMessage(d,function(a){a&&
(a.i18n&&k.setLocale(a.i18n),a.items&&(p=a.options||p,y(a.items)))}),document.getElementById("action").textContent=k.getMessage("Please_wait___")}catch(b){console.warn("Error(mSo): "+b.message)}};chrome.extension.onMessage.addListener(function(d,a,c){D&&console.log("onMessage: method "+d.method);"updateActions"==d.method?window.location.reload():D&&console.log("onMessage: Unknown method '"+d.method+"'")});(function(d,a){sendMessage({method:"loadTree",referrer:d},function(c){p=c.options||p;c.i18n&&
k.setLocale(c.i18n);a(c.items)})})("actions",function(d){I();y(d)})})});
