window.requestFileSystem||(window.requestFileSystem=window.webkitRequestFileSystem);window.BlobBuilder||(window.BlobBuilder=window.WebKitBlobBuilder);
Registry.require("layout xmlhttprequest convert crcrc curtain layout/default/tabview layout/default/htmlutil helper i18n parser statistics layout/default/layout_helper".split(" "),function(){var I=Registry.prepare(),m=Registry.get("crcrc").cr,d=Registry.get("crcrc").crc,k=Registry.get("i18n"),u=Registry.get("curtain"),q=Registry.get("helper"),J=Registry.get("layout/default/tabview"),t=Registry.get("layout/default/htmlutil"),B=Registry.get("statistics"),y=Registry.get("layout"),z=Registry.get("layout/default/layout_helper"),
C=z.images;y.render(function(){z.addStyle();z.addFont();var y=$.Deferred,f=null,D="???",v=null,E="0.0.0",w=function(){var a=document.getElementById("ask"),c=d("div","main_container p100100","ask","main");if(a){var b=a.parentNode;b.removeChild(a);b.appendChild(c);document.body.setAttribute("class","main")}var a=d("div","head_container","ask","head_container"),b=d("div","tv_container","ask","tv_container"),g=m("a","head_link","ask","head_link");g.href="http://tampermonkey.net";g.target="_blank";var e=
d("div","float margin4","ask","head1"),h=d("img","banner","ask");h.src=chrome.extension.getURL("images/icon128.png");var n=d("div","float head margin4","ask","head2"),k=m("div","fire"),f=d("div","version","version","version");f.textContent=" by Jan Biniok";var s=m("div","search","box","");k.textContent="Tampermonkey";e.appendChild(h);n.appendChild(k);n.appendChild(f);g.appendChild(e);g.appendChild(n);a.appendChild(g);a.appendChild(s);c.appendChild(a);c.appendChild(b);c=J.create("_main",b);a=m("div",
"main","main","tab_content_h");a.textContent=D;b=m("div","main","main","tab_content");c.appendTab(q.createUniqueId("main","main"),a,b).select();u.hide();return b},K=function(a){var c=a.script,b=d("div","viewer_bottom","bottom","");a=d("div","editor_400p_outer","editor",c.name);var g=d("div","editor_400p editor_border","editor",c.name);b.appendChild(a);a.appendChild(g);f.nocm?(a=d("textarea","editorta","editor",c.name),a.setAttribute("wrap","off"),g.appendChild(a),a.value=c.textContent):window.setTimeout(function(){b.editor=
new MirrorFrame(g,{value:c.textContent,noButtons:!0,matchBrackets:!0})},1);return b},L=function(){var a={};window.addEventListener("keydown",function(c){var b=!1;if("keydown"==c.type&&(a[c.keyCode]&&(b=a[c.keyCode](c)),b))return c.stopPropagation(),c.preventDefault(),!1},!0);return{registerListener:function(c,b){a[c]=b}}}(),x=function(a,c,b){q.select(b,function(a){return a.label}).forEach(function(b){var e=d("input",c,"tm",b.label);e.type="button";e.value=b.label;e.addEventListener("click",b.fn);
a.appendChild(e);b.focus&&window.setTimeout(function(){$(e).focus()},300);b.keyDown&&L.registerListener(b.keyDown.keyCode?b.keyDown.keyCode:b.keyDown,b.keyDown.cb?b.keyDown.cb:b.fn)})},O=function(a){var c=a.script,b=d("div","viewer_last","install"),g=d("div","viewer_content","install_content"),e=d("div","ask_action_buttons","install_buttons");x(e,"install",[{label:a.messages.action,fn:M,focus:!0},{label:a.messages.flags.install?k.getMessage("Process_with_Chrome"):null,fn:function(){N(c.fileURL);$(b).hide()}},
{label:k.getMessage("Cancel"),fn:r,keyDown:27}]);g.appendChild(e);b.appendChild(g);return b},P=function(a){var c=d("div","viewer_last","import"),b=d("div","viewer_content","import_content"),g=d("div","ask_action_buttons","import_buttons");x(g,"import",[{label:k.getMessage("Import"),fn:function(){var b=Object.keys(a);p(f.aid,"import",{data:{import_ids:b}})},focus:!0},{label:k.getMessage("Cancel"),fn:r,keyDown:27}]);b.appendChild(g);c.appendChild(b);return c},Q=function(a){a=d("div","viewer_last","ok");
var c=d("div","viewer_content","ok_content"),b=d("div","ask_action_buttons","ok_buttons");x(b,"import",[{label:k.getMessage("Ok"),fn:r,focus:!0}]);c.appendChild(b);a.appendChild(c);return a},R=function(a,c){var b=d("div","viewer_last","ok"),g=d("div","viewer_content","ok_content"),e=d("div","ask_action_buttons","ok_buttons");x(e,"permission",[{label:k.getMessage("Ok"),fn:function(){chrome.permissions.request({permissions:[c.permission]},function(a){chrome.runtime&&chrome.runtime.lastError&&console.warn("notify: error on getting permission",
c.permission+"!","reason:",chrome.runtime.lastError.message);p(f.aid,"permission",{data:{granted:a,permission:c.permission}})})},focus:!0},{label:k.getMessage("Cancel"),fn:r,keyDown:27}]);g.appendChild(e);b.appendChild(g);var g=d("div","viewer_upper","permission"),e=d("div","viewer_info","general","permission"),h=d("div","viewer_content","general_content","permission"),n=m("h3","install","heading","permission"),F=d("span","message","heading","permission");n.textContent=c.title;F.textContent=c.message;
h.appendChild(F);e.appendChild(n);e.appendChild(h);g.appendChild(e);a.appendChild(g);a.appendChild(b)},A=function(a,c){var b=a.preparat,g=a.content,e=b.script||{},h=e.uuid||e.id||e.name;b.short_info||(b.short_info=[]);var n=d("div","viewer_upper",h),f=d("div","viewer_info","general",h),p=d("div","viewer_content","general_content",h),s=m("h3","install","heading",h);if(e.icon||e.icon64){var l=m("img","version","heading",h);l.src=e.icon||e.icon64;s.appendChild(l)}l=m("span","name","heading",h);l.textContent=
b.heading||e.name||"";s.appendChild(l);e.version&&(l=d("span","view_version","heading",h),l.textContent="v"==e.version[0]?"":"v",l.textContent+=e.version,s.appendChild(l));f.appendChild(s);c&&b.short_info.unshift({prop:"heading",value:b.messages.heading,label:k.getMessage("Action")});var r=d("table","script_desc",h);b.short_info.forEach(function(a){var b=e[a.prop]||a.value;if(b||!c){var g=d("tr","script_desc",a.prop,h),n=d("td","script_desc",a.prop,h+"dt"),f=d("td","script_desc",a.prop,h+"dd");n.textContent=
a.label?a.label:"";f.textContent=b||k.getMessage("_not_set_");g.appendChild(n);g.appendChild(f);r.appendChild(g)}});p.appendChild(r);var s=d("div","viewer_info","info",h),q;c?q=p:(q=d("div","viewer_content","info_content",h),l=m("h4","action","heading",h),l.textContent=b.messages.heading,q.appendChild(l));["errors","warnings","info"].forEach(function(a){var c=m("table",a,h);(b.messages[a]||[]).forEach(function(b){var e=m("tr",a,h),d=m("td",a,h+"dt"),g=m("td",a,h+"dd");"info"==a?(d.textContent=b.label,
g.textContent=b.value):"warnings"==a?(d.innerHTML='<img src="'+C.get("critical")+'"></img>&nbsp;',g.innerHTML=t.safeTagsReplace(b).replace(/\n/,"<br />")):"errors"==a&&(d.innerHTML='<img src="'+C.get("error")+'"></img>&nbsp;',g.innerHTML=t.safeTagsReplace(b).replace(/\n/,"<br />"));e.appendChild(d);e.appendChild(g);c.appendChild(e)});q.appendChild(c)});l=function(a,b,c,g){var n=m("table",a,h),f=0,l={};b.forEach(function(b){if(!(f>g||l[b])){l[b]=!0;var e=d("tr",a+"desc",b,h+f),k=d("td",a+"desc",b,
h+f+"dt"),m=d("td",a+"desc",b,h+f+"dd");k.innerHTML=0==f?t.safeTagsReplace(c.label):"&nbsp;";m.innerHTML=f==g?'<span title="'+t.safeTagsReplace(c.warning)+'">...!</span>':t.safeTagsReplace(b);e.appendChild(k);e.appendChild(m);n.appendChild(e);f++}});if(e.options&&(b=e.options.override&&e.options.override["use_"+a])&&b.length){b=d("tr",a+"desc","ovverride",h+f);var p=d("td",a+"desc","ovverride",h+f+"dt"),r=d("td",a+"desc","ovverride",h+f+"dd");p.innerHTML=0==f?t.safeTagsReplace(c.label):"&nbsp;";r.innerHTML=
t.safeTagsReplace(" ("+k.getMessage("overwritten_by_user")+")");b.appendChild(p);b.appendChild(r);n.appendChild(b)}q.appendChild(n)};l("includes",(e.includes||[]).concat(e.matches||[]),{label:k.getMessage("Include_s__"),warning:k.getMessage("Attention_Can_not_display_all_includes_")},5);l("excludes",e.excludes||[],{label:k.getMessage("Exclude_s__"),warning:k.getMessage("Attention_Can_not_display_all_excludes_")},3);f.appendChild(p);s.appendChild(q);n.appendChild(f);n.appendChild(s);g.appendChild(n);
a.install&&g.appendChild(a.install(b));a.editor&&g.appendChild(a.editor(b))},N=function(a){p(f.aid,"abort");window.setTimeout(function(){window.location=a+"#bypass=true"},10)},r=function(a,c){p(f.aid,"abort");window.setTimeout(function(){window.close()},100)},G=function(a,c){p(f.aid,"unload");v&&(window.clearInterval(v),v=null);window.removeEventListener("unload",G)};window.addEventListener("unload",G);var H=function(){window.location.search||window.location.hash?(f=q.getUrlArgs(),f.aid?(p(f.aid,
"preparat").done(function(a){a.ext&&a.ext.version&&(E=a.ext.version);a.i18n&&k.setLocale(a.i18n);a.options&&a.options.statistics_enabled&&S();D=k.getMessage("Install");var c=null;a.preparat&&("install"==a.type?c=function(){A({content:w(),preparat:a.preparat,install:O,editor:K})}:"install_error"==a.type?c=function(){A({content:w(),preparat:a.preparat,install:Q},!0)}:"import"==a.type?c=function(){var b=w(),c=a.preparat;b.appendChild(P(c));for(var e in c){var h=c[e],f=d("div","viewer_upper",e);A({content:f,
preparat:h},!0);b.appendChild(f)}}:"permission"==a.type&&(c=function(){R(w(),a.preparat)}),v=window.setInterval(T,6E4),c&&window.setTimeout(c,1))}).fail(function(){r()}),u.wait(k.getMessage("Please_wait___"))):r()):window.onhashchange=function(){H()}},T=function(){return p(f.aid,"ping",{bg:!0})},M=function(){return p(f.aid,"install")},p=function(a,c,b){b=b||{};var d=y();try{var e={aid:a,method:c};b.data&&q.each(b.data,function(a,c){e[c]=b.data[c]});sendMessage({method:"askCom",data:e},function(a){b.bg||
u.hide();a.error?("close"==a.action&&r(),d.reject(a)):d.resolve(a)});b.bg||u.wait(k.getMessage("Please_wait___"))}catch(f){console.warn("sS: "+f.message),d.reject()}return d.promise()},S=function(){B.init(I.SELF.ID);window.onerror=function(a,c,b,d,e){B.tE(a,E+" ask@"+c,[b+":"+d,e?e.stack:""].join(";"))}};chrome.extension.onMessage.addListener(function(a,c,b){if("confirm"==a.method)q.confirm(a.msg,function(a){b({confirm:a})});else if("showMsg"==a.method)q.alert(a.msg),b({});else return!1;return!0});
H()})});
