(function(){Registry.require(["prepare"],function(){var g=Registry.prepare(),t=!1,h=!1,v=[],m=!0,f=$.Deferred,p=function(a){var b=f();b.resolve(a);return b.promise()},u=function(){var a=[g.CONSTANTS.STORAGE.VERSION,g.CONSTANTS.STORAGE.TYPE],b={};a.forEach(function(a){b[a]=!0});return{keys:a,has:function(a){return!!b[a]}}}(),B=function(){return window.openDatabase("tmStorage","1.0","TM Storage",31457280)},C=function(a){return a},w=function(a,b){if(!a)return b;var c=a[0];a=a.substring(1);switch(c){case "b":return"true"==
a;case "n":return Number(a);case "o":try{return JSON.parse(a)}catch(d){console.error("Storage: getValue ERROR: "+d.message)}return b;default:return a}},x=function(a){var b=(typeof a)[0];switch(b){case "o":try{a=b+JSON.stringify(a)}catch(c){console.error("Storage: setValue ERROR: "+c.message);return}break;default:a=b+a}return a},s=function(a,b){var c=f(),d=Array.prototype.slice.call(arguments,2),e;"string"==typeof a?a==g.DB.USE&&"clean"==b?console.warn("Storage: can't clean currently active storage"):
e=k.implementations[a][b]:e=a[b];if(e)if(d=e.apply(this,d),"object"===typeof d&&d.then)d.then(function(){c.resolve.apply(this,arguments)},function(a){c.reject()});else return d;else c.resolve();return c.promise()},y=function(a,b){var c=f(),d=[];Object.getOwnPropertyNames(b).forEach(function(c){void 0!==b[c]&&d.push(s(a,"setValue",c,b[c]))});$.when.apply($,d).done(function(){c.resolve()});return c.promise()},z=function(a,b){var c={};b.forEach(function(b){c[b]=s(a,"getValue",b)});return c},k={implementations:{localStorage:function(){var a=
{setValue:function(a,c){var d=f();h&&console.log("localStorage: setValue -> "+a);var e=x(c);m&&localStorage.setItem(a,e);d.resolve();return d.promise()},getValue:function(a,c){h&&console.log("Storage: getValue -> "+a);return w(localStorage.getItem(a,c),c)},deleteAll:function(){var b=f();h&&console.log("localStorage: deleteAll()");m&&a.listValues().forEach(function(a){u.has(a)||localStorage.removeItem(a)});b.resolve();return b.promise()},deleteValue:function(a){var c=f();h&&console.log("localStorage: deleteValue -> "+
a);m&&localStorage.removeItem(a);c.resolve();return c.promise()},listValues:function(){h&&console.log("localStorage: listValues");for(var a=[],c=0;c<localStorage.length;c++)a.push(C(localStorage.key(c)));return a}};return{options:{},methods:a}}(),sql:function(){var a=null,b=null,c=function(){var a=f();b.db.transaction(function(c){c.executeSql("CREATE TABLE IF NOT EXISTS config(ID INTEGER PRIMARY KEY ASC, name TEXT, value TEXT)",[],a.resolve,b.onError)});return a.promise()},d=function(){var a=f();
b={db:B(),onSuccess:function(a,b){h&&console.log("webSQL: localDB Success ")},onError:function(a,b){console.error("webSQL: localDB Error ",b)}};c().done(a.resolve);return a.promise()},e={setValue:function(c,q){var n=f();h&&console.log("Storage: setValue -> "+c);var d=x(q);m&&(a[c]?b.db.transaction(function(a){a.executeSql("UPDATE config SET value=? WHERE name=?",[d,c],function(){chrome.runtime&&chrome.runtime.lastError&&console.warn(chrome.runtime.lastError);n.resolve()},b.onError)}):b.db.transaction(function(a){a.executeSql("INSERT INTO config(name, value) VALUES (?,?)",
[c,d],function(){chrome.runtime&&chrome.runtime.lastError&&console.warn(chrome.runtime.lastError);n.resolve()},b.onError)}));a[c]=d;m||n.resolve();return n.promise()},getValue:function(b,c){h&&console.log("webSQL: getValue -> "+b);return w(a[b],c)},deleteAll:function(){var d=f();h&&console.log("webSQL: deleteAll()");var q=z(e,u.keys);a=q;m?b.db.transaction(function(a){a.executeSql("DROP TABLE config",[],function(){c().done(function(){y(e,q).done(d.resolve)})},b.onError)}):d.resolve();return d.promise()},
deleteValue:function(c){var q=f();h&&console.log("webSQL: deleteValue -> "+c);delete a[c];m?b.db.transaction(function(a){a.executeSql("DELETE FROM config WHERE name=?",[c],q.resolve,b.onError)}):q.resolve();return q.promise()},listValues:function(){h&&console.log("webSQL: listValues");var b=[];Object.getOwnPropertyNames(a).forEach(function(a){b.push(a)});return b},isWorking:function(){return p()}};return{init:function(){var c=f(),q=function(b,l){a={};if(l)for(var r=0;r<l.rows.length;r++)a[l.rows.item(r).name]=
l.rows.item(r).value;c.resolve()},n=function(){a?c.resolve():b.db.transaction(function(a){a.executeSql("SELECT * FROM config",[],q,b.onError)})};b?n():d().done(n);return c.promise()},clean:function(){a=null;return p()},options:{},methods:e}}(),chromeStorage:function(){var a=null,b=!1,c=!1,d=chrome.extension.inIncognitoContext?"incognito":"normal",e=function(b,n){if(m&&c&&"local"==n)for(var e in b){var l=b[e];h&&console.log("si: local storage key",e,"@",n,"changed:",l);l.newValue?l.newValue.origin!==
d&&(a[e]=l.newValue.value,k.notifyDifferentOriginChangeListeners(e,l.newValue)):delete a[e]}},g={setValue:function(b,c){var e=f();h&&console.log("chromeStorage: setValue -> ",b,c);a[b]=c;if(m){var l={};l[b]={origin:d,value:c};chrome.storage.local.set(l,e.resolve)}else e.resolve();return e.promise()},getValue:function(b,c){var d=void 0===a[b]?c:a[b];h&&console.log("chromeStorage: getValue -> ",b,d);return d},deleteAll:function(){var b=f();h&&console.log("chromeStorage: deleteAll()");var c=z(g,u.keys);
a=c;m?chrome.storage.local.clear(function(){y(g,c).done(b.resolve)}):b.resolve();return b.promise()},deleteValue:function(b){var c=f();h&&console.log("chromeStorage: deleteValue -> "+b);delete a[b];m?chrome.storage.local.remove(b,c.resolve):c.resolve();return c.promise()},listValues:function(){h&&console.log("chromeStorage: listValues");var b=[];Object.getOwnPropertyNames(a).forEach(function(a){b.push(a)});return b},setTemporary:function(a){m=!a;c=!0},isSupported:function(){return p()},isWorking:function(){var a=
f(),b=(new Date).getTime(),c={};c.foo=b;var l=function(){console.warn("storage:",chrome.runtime&&chrome.runtime.lastError?chrome.runtime.lastError.message:"storage set/get test failed!");a.reject()},r=window.setTimeout(function(){r=null;l()},18E4);chrome.storage.local.set(c,function(){chrome.storage.local.get("foo",function(c){if(r){window.clearTimeout(r);r=null;if(!c||c.foo!==b||chrome.runtime&&chrome.runtime.lastError)return l();chrome.storage.local.remove("foo",a.resolve)}})});return a.promise()}};
return{init:function(){var c=f();a?c.resolve():chrome.storage.local.get(null,function(d){a={};for(var f in d){var l=d[f];a[f]=l&&l.hasOwnProperty("origin")&&l.hasOwnProperty("value")?l.value:l}b||(chrome.storage.onChanged.addListener(e),b=!0);c.resolve()});return c.promise()},clean:function(){var b=f();a=null;b.resolve();return b.promise()},options:{},methods:g}}(),file:function(){var a=null,b=null,c=function(){var a=f(),c=function(b){console.warn("fileStorage: listFiles() error:",b);a.reject()};
b.root.getDirectory("data",{create:!0},function(b){var d=b.createReader(),e=[],f=function(){d.readEntries(function(b){b.length?(e=e.concat(b),f()):a.resolve(e)},c)};f()},c);return a.promise()},d=function(a,c){var d=f(),e=function(b){console.warn("fileStorage: writeFileData(",a,") error:",b);d.reject()};b.root.getDirectory("data",{create:!0},function(b){b.getFile(a,{create:!0},function(a){a.createWriter(function(a){a.onwriteend=function(b){a.onwriteend=function(a){d.resolve()};a.onerror=e;b=new Blob([c],
{type:"text/plain"});a.write(b)};a.truncate(0)},e)},e)},e);return d.promise()},e=function(a){var c=f(),d=function(b){console.warn("fileStorage: getFileData(",a,") error:",b);c.reject()},e=function(a){var b=new FileReader;b.onloadend=function(){c.resolve(this.result)};b.onerror=d;b.onabort=d;b.readAsText(a)};b.root.getDirectory("data",{create:!0},function(b){b.getFile(a,{},function(a){a.file(function(a){e(a)},d)},d)},d);return c.promise()},g=function(a){var c=f(),d=function(b){console.warn("fileStorage: deleteFile(",
a,") error:",b);c.reject()};b.root.getDirectory("data",{create:!0},function(b){b.getFile(a,{create:!1},function(a){a.remove(c.resolve,d)},d)},d);return c.promise()},k=function(){var a=f(),c=function(b){console.warn("fileStorage: removeDir() error:",b);a.reject()};b.root.getDirectory("data",{create:!0},function(b){b.removeRecursively(a.resolve,c)},c);return a.promise()},n=function(){var b=f();a={};var d=[];c().done(function(c){c.forEach(function(b){"string"!==typeof b&&(b=b.name);d.push(e(b).always(function(c){a[b]=
c}))});$.when.apply($,d).always(function(){b.resolve()})}).fail(b.resolve);return b.promise()},A={isSupported:function(){var a=f();window.File&&window.FileReader&&window.FileList&&window.Blob?a.resolve():a.reject();return a.promise()},isWorking:function(){return p()},setValue:function(b,c){var e=f();h&&console.log("fileStorage: setValue -> "+b);var g=x(c);a[b]=g;m?d(b,g).always(e.resolve):e.resolve();return e.promise()},getValue:function(b,c){h&&console.log("fileStorage: getValue -> "+b);return w(a[b],
c)},deleteAll:function(){var b=f();h&&console.log("fileStorage: deleteAll()");var c=z(A,u.keys);a=c;m?k().always(function(){y(A,c).always(b.resolve)}):b.resolve();return b.promise()},deleteValue:function(b){var c=f();h&&console.log("fileStorage: deleteValue -> "+b);delete a[b];m?g(b).always(c.resolve):c.resolve();return c.promise()},listValues:function(){h&&console.log("fileStorage: listValues");var b=[];Object.getOwnPropertyNames(a).forEach(function(a){b.push(a)});return b}};return{init:function(){var c=
f();a?c.resolve():(window.requestFileSystem=window.requestFileSystem||window.webkitRequestFileSystem,window.requestFileSystem(window.PERSISTENT,31457280,function(a){b=a;n().done(c.resolve)},function(a){a&&console.warn("fileStorage: ",a);c.reject()}));return c.promise()},clean:function(){a=null;return p()},options:{},methods:A}}()},migrate:function(a,b,c){var d=f(),e=k.implementations[a],g=k.implementations[b];c=c||{};e&&g?(h&&console.log("Migration: from",a,"to",b),s(a,"init").then(function(){return s(b,
"init")}).then(function(){var a=f(),b=[];e.methods.listValues().forEach(function(a){var d=e.methods.getValue(a);c.drop&&b.push(e.methods.deleteValue(a));h&&console.log("Migration: copy value of "+a);b.push(g.methods.setValue(a,d))});$.when.apply($,b).done(function(){a.resolve()});return a.promise()}).then(function(){return s(b,"clean")}).then(function(){return s(a,"clean")}).done(function(){d.resolve()}).fail(function(){d.reject()})):(console.error("Migration: unknown storage implementation(s) ",
a,b),d.reject());return d.promise()},isSupported:function(){return p()},isWorking:function(){return p()},setTemporary:function(a){m=!a},init:function(){t&&console.log("Storage: use "+g.DB.USE);Object.getOwnPropertyNames(k.implementations[g.DB.USE].methods).forEach(function(a){k.__defineGetter__(a,function(){return k.implementations[g.DB.USE].methods[a]})});return k.implementations[g.DB.USE].init?k.implementations[g.DB.USE].init():p()},getValues:function(a,b){var c={};b||(b={});Object.getOwnPropertyNames(a).forEach(function(a){c[a]=
k.implementations[g.DB.USE].getValue(a,b[a])});return c},factoryReset:function(){localStorage.removeItem(g.CONSTANTS.STORAGE.LEGACY_VERSION);return k.deleteAll()},isWiped:function(){if("localStorage"===g.DB.USE)return p(!1);var a=f(),b=k.getValue(g.CONSTANTS.STORAGE.VERSION),c=!1;localStorage.getItem(g.CONSTANTS.STORAGE.LEGACY_VERSION)&&!b&&(k.listValues().length?console.warn("storage: unable to find version information"):c=!0);a.resolve(c);return a.promise()},setVersion:function(a,b){var c=f();m?
(localStorage.setItem(g.CONSTANTS.STORAGE.LEGACY_VERSION,a),k.setValue(g.CONSTANTS.STORAGE.VERSION,a).then(function(){return b?k.setValue(g.CONSTANTS.STORAGE.SCHEMA,b):p()}).always(c.resolve)):c.resolve();return c.promise()},getVersion:function(a){var b=f(),c=k.getValue(g.CONSTANTS.STORAGE.VERSION)||k.getValue(g.CONSTANTS.STORAGE.LEGACY_VERSION)||localStorage.getItem(g.CONSTANTS.STORAGE.LEGACY_VERSION);c?b.resolve(c):s("sql","init").then(function(b){c=k.implementations.sql.methods.getValue(g.CONSTANTS.STORAGE.LEGACY_VERSION)||
a;return s("sql","clean")}).always(function(){t&&console.log("Storage: unable to determine ");b.resolve(c)});return b.promise()},getSchemaVersion:function(){return k.getValue(g.CONSTANTS.STORAGE.SCHEMA,"3.5")},debug:function(a,b){h|=b;t|=a},addDifferentOriginChangeListener:function(a,b){v.push({search:a,cb:b})},notifyDifferentOriginChangeListeners:function(a,b){for(var c in v){var d=v[c];0==a.search(d.search)&&d.cb(a,b)}},recover:function(a,b){"string"===typeof a&&(a={method:a,storages:["sql","chromeStorage"]});
var c={};a.storages.forEach(function(a){c[a]=!0});if("log"==a.method){var d=null,e,f,g=[{method:"sql",fn:function(a){console.debug("check sql storage for data...");try{f=B();if(chrome.runtime&&chrome.runtime.lastError)return d=chrome.runtime.lastError,a();f.transaction(function(b){b.executeSql("CREATE TABLE IF NOT EXISTS config(ID INTEGER PRIMARY KEY ASC, name TEXT, value TEXT)",[],function(){console.debug("sql table found/created");a()},function(b,c){d=c;a()})})}catch(b){d=b,window.setTimeout(a,
1)}}},{method:"sql",fn:function(a){var b={};f.transaction(function(c){c.executeSql("SELECT * FROM config",[],function(c,d){if(d)for(var f=0;f<d.rows.length;f++)b[d.rows.item(f).name]=d.rows.item(f).value;e=b;window.setTimeout(a,1)},function(b,c){d=c;a()})})}},{method:"sql",fn:function(a){var b=e?Object.getOwnPropertyNames(e):[];e&&b.length?(console.debug("found values:"),b.forEach(function(a){console.debug("    ",a,e[a]&&30<e[a].length?e[a].substr(0,30):e[a])})):(console.warn("no data found"),c.sql=
!1);window.setTimeout(a,1)}},{method:"chromeStorage",fn:function(a){console.debug("check chromeStorage for data...");chrome.storage.local.get(null,function(b){e=b;a()})}},{method:"chromeStorage",fn:function(a){var b=e?Object.getOwnPropertyNames(e):[];e&&b.length?(console.debug("found values:"),b.forEach(function(a){console.debug("    ",a,e[a]&&30<e[a].length?e[a].substr(0,30):e[a])})):(console.warn("no data found"),c.chromeStorage=!1,window.setTimeout(a,1))}}],h=0,k=function(){if(d)console.warn("error:",
d);else for(;g[h];){if(c[g[h].method]){g[h].fn(k);h++;return}h++}b&&b()};k()}}};Registry.register("storage","202",function(){return k})})})();
