Registry.require(["prepare","helper","convert","xmlhttprequest"],function(){var F=Registry.prepare(),C=Registry.get("helper"),G=Registry.get("xmlhttprequest").run,H=Registry.get("convert"),f=$.Deferred,u=function(e){var k=f();k.resolve(e);return k.promise()},M=function(){var e=f();e.reject();return e.promise()},p=0,q=0,v={ePASTEBIN:1,eCHROMESYNC:2,eGOOGLEDRIVE:3},z=[],B=!1,w=null,K=[{method:"HEAD",url:"http://www.google.com",extract:function(f,k){try{var l=k?k.split("\n"):null,m;for(m in l){var D=
l[m].split(":"),n=D.shift()||"",I=D.join(":")||"";if("date"==n.trim().toLowerCase()&&I){var J=new Date(I);if(J)return J.getTime()-(new Date).getTime()}}}catch(p){}return null}},{method:"GET",url:"http://json-time.appspot.com/time.json",extract:function(f,k){try{var l=JSON.parse(f);if(!l.error&&l.datetime){var m=new Date(l.datetime);if(m)return m.getTime()-(new Date).getTime()}}catch(D){}return null}}],t=function(){var e=function(){var e,n=!1,m=null,k=function(a){},l=function(a){m=a.state;console.log("si: sync filesystem state changed to : "+
m)},p=function(){var a=f(),h=function(b){console.warn("si: listFiles() error:",b);a.reject()};e.root.getDirectory("/",{create:!0},function(b){var g=b.createReader(),c=[],d=function(){g.readEntries(function(b){b.length?(c=c.concat(b),d()):a.resolve(c)},h)};d()},h);return a.promise()},q=function(a,h){var b=f(),g=function(h){console.warn("si: writeFileData(",a,") error:",h);b.reject()};e.root.getDirectory("/",{create:!0},function(c){c.getFile(a,{create:!0},function(a){a.createWriter(function(a){a.onwriteend=
function(c){a.onwriteend=function(a){b.resolve()};a.onerror=g;c=new Blob([h],{type:"text/plain"});a.write(c)};a.truncate(0)},g)},g)},g);return b.promise()},s=function(a){var h=f(),b=function(b){console.warn("si: getFileData(",a,") error:",b);h.reject()},c=function(a){var c=new FileReader;c.onloadend=function(){h.resolve(this.result)};c.onerror=b;c.onabort=b;c.readAsText(a)};e.root.getDirectory("/",{create:!0},function(h){h.getFile(a,{},function(a){a.file(function(a){c(a)},b)},b)},b);return h.promise()},
r=function(a){var c=f(),b=function(b){console.warn("fileStorage: deleteFile(",a,") error:",b);c.reject()};e.root.getDirectory("/",{create:!0},function(g){g.getFile(a,{create:!1},function(a){a.remove(c.resolve,b)},b)},b);return c.promise()},d=null,y={},c=function(){return A(function(){var a=f(),c=[];C.each(y,function(a,g){c.push(function(){var c=f();q(g,a).always(function(){c.resolve()});return c.promise()}())});y={};$.when.apply($,c).done(function(){a.resolve()});return a.promise()})};return{init:function(){if(!n){try{chrome.syncFileSystem.onFileStatusChanged.addListener(k)}catch(a){console.log("si: error registering file status callback: "+
a.message)}if(F.SYNC.GOOGLE_DRIVE.HAS_SERVICE_STATUS)try{chrome.syncFileSystem.onServiceStatusChanged.addListener(l)}catch(c){console.log("si: error registering service status callback: "+c.message)}n=!0}var b=f();chrome.syncFileSystem?chrome.syncFileSystem.requestFileSystem(function(a){chrome.runtime.lastError?b.resolve(!1):(e=a,b.resolve(!0))}):b.resolve(!1);return b.promise()},list:function(){return p().then(function(a){var c=[],b=[],g=f(),d=/.user.js$/;a.forEach(function(a){-1!=a.search(d)&&b.push(function(){var b=
f();s(a).done(function(a){var b;try{b=JSON.parse(a)}catch(g){}b&&c.push({uuid:b.uuid,url:b.url,options:b.options?b.options:{},content:b.content})}).always(function(){b.resolve()});return b.promise()}())});$.when.apply($,b).done(function(){g.resolve(c)});return g.promise()})},add:function(a){y[a.uuid+".user.js"]=JSON.stringify({uuid:a.uuid,url:a.url,options:a.options,content:a.content});d&&window.clearTimeout(d);d=window.setTimeout(c,3E3);return u()},write:c,remove:function(a){var h={uuid:a.uuid,url:a.url,
options:a.options||{}};h.options.removed=(new Date).getTime()+w;y[a.uuid+".user.js"]=JSON.stringify(h);d&&window.clearTimeout(d);d=window.setTimeout(c,3E3);return u()},reset:function(){return p().then(function(a){var c=[],b=f();a.forEach(function(a){c.push(function(){var b=f();r(a).always(function(){b.resolve()});return b.promise()}())});$.when.apply($,c).done(function(){b.resolve()});return b.promise()})}}}(),k=function(){var e=!1,n,m=function(c,a){if(p==v.eCHROMESYNC&&"sync"==a)if(null===w)E().done(function(){m(c,
a)});else{var h=RegExp(n+"$"),b;for(b in c){var g=c[b];console.log('si: storage key "%s" in namespace "%s" changed. Old value was "%s", new value is "%s".',b,a,g.oldValue,g.newValue);if(-1==b.search(h))console.log("si:   ^^ ignore cause this is not related to us!");else for(var d=0;d<z.length;d++)if(r[b])console.log("si:   ^^ ignore cause object is going to be changed right now or was changed by me!");else{var f=t(g.newValue,b);if(f)z[d](b,f)}}}},k=function(c,a){var h=f(),b=[];a?l().done(function(g){"url"==
c&&(a=a.split("#")[0]);b=C.select(g,function(b){return b.item&&b.item[c]==a});h.resolve(b)}).fail(function(a){h.reject(a)}):h.resolve(b);return h.promise()},l=function(){return A(function(){var c=f(),a=RegExp(n+"$");chrome.storage.sync.get(null,function(h){var b=[],g;for(g in h)-1!=g.search(a)&&b.push({key:g,item:t(h[g],g)});c.resolve(b)});return c.promise()})},t=function(c,a){var h=null;try{h=JSON.parse(c)}catch(b){}return h&&h.url?h:(console.warn("si: unable to parse extended info of "+a),null)},
x=function(c){return c.then(function(a){var c={};a=C.select(a,function(a,b){if(!c[a.key])return c[a.key]=!0});if(1<a.length){var b=f(),g=[],e=a.pop();a.forEach(function(a){g.push(d(a.key))});$.when.apply($,g).done(function(){b.resolve(e)});return b.promise()}return u(a[0])})},s=null,r={},d=function(c,a){return A(function(){var a=f();chrome.storage.sync.remove(c,function(b){(b=chrome.runtime?chrome.runtime.lastError:b)?a.reject(b):a.resolve()});return a.promise()})},y=function(c){return A(function(){var a=
f();chrome.storage.sync.set(r,function(c){(c=chrome.runtime?chrome.runtime.lastError:c)?a.reject(c):(r={},a.resolve())});return a.promise()})};return{init:function(){var c=!0;if(!e)try{chrome.storage.onChanged.addListener(m),e=!0}catch(a){console.log("si: error registering sync callback: "+a.message),c=!1}2==q?n="@v2":(q=1,n="@us");return u(c)},list:function(){var c;c=null===w?E():u();return c.then(function(){return l()}).then(function(a){var c=RegExp(n+"$"),b=[];a.forEach(function(a){var d=a.key;
a=a.item;var f=d.replace(c,""),e=null;(e=r[d]?t(r[d],d):a)&&(1==q||(!e.vmin||q>=e.vmin)&&(!e.vmax||q<=e.vmax))&&b.push({id:f,uuid:e.uuid,url:e.url,options:e.options||{}})});return u(b)})},add:function(c){var a=f(),d=2==q?k("uuid",c.uuid):k("url",c.url);x(d).done(function(b){var d;b?(d=b.key,b=b.item):(d=c.uuid+n,b={});b.url=c.url;b.options=c.options||{};2==q&&(b.uuid=c.uuid);r[d]=JSON.stringify(b);s&&window.clearTimeout(s);s=window.setTimeout(y,3E3);a.resolve()});return a.promise()},remove:function(c){var a=
f(),d=2==q?k("uuid",c.uuid):k("url",c.url);x(d).done(function(b){var d;b?(d=b.key,b=b.item):(d=c.uuid+n,b={});b.options=b.options||{};b.options.removed=(new Date).getTime()+w;r[d]=JSON.stringify(b);s&&window.clearTimeout(s);s=window.setTimeout(y,3E3);a.resolve()});return a.promise()},reset:function(){return A(function(){var c=f();chrome.storage.sync.clear(function(){r={};c.resolve()});return c.promise()})}}}(),l=function(){var e,k=null,m=function(){var d=f();e?G({method:"GET",retries:3,url:e},{onload:function(e){4==
e.readyState&&(200==e.status?d.resolve(e.responseText):d.reject())},onerror:d.reject}):d.reject({});return d.promise()},l=function(){var d=f();m().done(function(e){q(e).done(function(c){k=H.MD5(e);d.resolve(c)})}).fail(function(e){d.reject(e)});return d.promise()},q=function(d){var e=f(),c=[];try{d=d.replace(/\t/g,"    ");d=d.replace(/\r/g,"\n");d=d.replace(/\n\n+/g,"\n");for(var a=d.split("\n"),h=0;h<a.length;h++){var b=a[h],g=b.split("|");if(3<g.length)console.log("si: can't handle line: "+b);else{var k=
g[g.length-1],m=null,l=null;if(1<g.length)for(var n=g.length-2;0<=n;n--)try{m=JSON.parse(g[n])}catch(p){l=g[n]}c.push({name:l,url:k,options:m||{}})}}}catch(q){console.warn("si: unable to parse data: "+d)}e.resolve(c);return e.promise()},t=function(){var d=f();m().done(function(d){q(d).done(function(c){if(k!=H.MD5(d))for(c=0;c<z.length;c++)z[c]()})}).fail(function(e){d.reject(e)});return d.promise()},x=null,s=function(d){if(x)if(d)window.clearTimeout(x);else return;console.debug("si: schedule sync for periodical run every 18000000 ms");
x=window.setTimeout(function(){x=null;p==v.ePASTEBIN&&t().always(function(){s()})},18E6)},r={init:function(d){e="http://pastebin.com/raw.php?i=%s".replace("%s",d);s(!0);return u(!0)},list:function(){return null===w?E().then(function(){return r.list()}):l()}};return r}(),m={};m[v.ePASTEBIN]=l;m[v.eCHROMESYNC]=k;F.SYNC.GOOGLE_DRIVE.SUPPORTED&&(m[v.eGOOGLEDRIVE]=e);return m}(),E=function(){var e=f(),k=0,l=function(){if(k<K.length){var f=K[k],p={method:f.method,url:f.url};console.log("si: determine time offset with server "+
f.url);G(p,{ondone:function(n){4==n.readyState&&(200==n.status?(n=f.extract(n.responseText,n.responseHeaders),null===n?(k++,window.setTimeout(l,1)):(w=n,console.log("si: detected a time offset of "+n+" ms"),e.resolve(!0))):(k++,window.setTimeout(l,1)))}})}else w=0,console.log("si: time offset detection failed!"),e.resolve(!1)};l();return e.promise()},A=function(e,k){var l=f();void 0===k&&(k=3);var m=function(){if(B)window.setTimeout(m,500);else{B=!0;try{e().always(function(){B=!1}).done(function(){l.resolve.apply(this,
arguments)}).fail(function(){0<--k?(console.log("si: some retries left, wait for",6E4,"ms"),window.setTimeout(m,6E4)):(console.warn("si: no retries left, skipping this sync request!"),l.reject("no retries left"))})}catch(f){console.warn(f),B=!1,l.reject(f)}}};m();return l.promise()},L={init:function(e,f,l){z=[];p=e;q=f;return t[p]?t[p].init(l).done(function(e){}):M()},debug:function(e){},addChangeListener:function(e){z.push(e)},isWritable:function(){return p==v.eCHROMESYNC||p==v.eGOOGLEDRIVE},types:v};
["list","add","reset","remove"].forEach(function(e){L[e]=function(){return t[p]&&t[p][e]?t[p][e].apply(this,arguments):u()}});Registry.register("syncinfo","202",L)});
